import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "ar";

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<string, Record<Lang, string>> = {
  // Nav
  "nav.features": { en: "Features", ar: "المميزات" },
  "nav.howItWorks": { en: "How It Works", ar: "كيف تعمل" },
  "nav.pricing": { en: "Pricing", ar: "الأسعار" },
  "nav.testimonials": { en: "Testimonials", ar: "آراء العملاء" },
  "nav.signIn": { en: "Sign In", ar: "تسجيل الدخول" },
  "nav.startTrial": { en: "Start Free Trial", ar: "ابدأ التجربة المجانية" },
  // Hero
  "hero.badge": { en: "15-Day Free Trial — No Credit Card Required", ar: "تجربة مجانية 15 يوماً — بدون بطاقة ائتمانية" },
  "hero.title1": { en: "The Clinic OS for", ar: "نظام إدارة العيادة لـ" },
  "hero.title2": { en: "Modern Medicine", ar: "الطب الحديث" },
  "hero.subtitle": { en: "ClinicSquad gives Egyptian doctors and clinic owners a complete management platform — patients, appointments, finances, and staff — in one powerful workspace.", ar: "كلينيك سكواد يمنح الأطباء المصريين وأصحاب العيادات منصة إدارة متكاملة — المرضى والمواعيد والمالية والموظفين — في مكان عمل واحد قوي." },
  "hero.cta1": { en: "Start Your Free Trial", ar: "ابدأ تجربتك المجانية" },
  "hero.cta2": { en: "Sign In to Dashboard", ar: "تسجيل الدخول للوحة التحكم" },
  "hero.stat.clinics": { en: "Clinics", ar: "عيادة" },
  "hero.stat.patients": { en: "Patients", ar: "مريض" },
  "hero.stat.trial": { en: "Free Trial", ar: "تجربة مجانية" },
  // Features
  "feat.title": { en: "Everything Your Clinic Needs", ar: "كل ما تحتاجه عيادتك" },
  "feat.subtitle": { en: "A complete clinical management system built specifically for Egyptian healthcare practices.", ar: "نظام إدارة عيادات متكامل مصمم خصيصاً للرعاية الصحية المصرية." },
  "feat.patients.title": { en: "Patient Management", ar: "إدارة المرضى" },
  "feat.patients.desc": { en: "Comprehensive patient records with medical history, allergies, and contact details.", ar: "سجلات مرضى شاملة مع التاريخ الطبي والحساسيات وبيانات التواصل." },
  "feat.scheduling.title": { en: "Smart Scheduling", ar: "جدولة ذكية" },
  "feat.scheduling.desc": { en: "Effortless appointment booking with status tracking and daily views.", ar: "حجز مواعيد بسهولة مع تتبع الحالة وعرض يومي." },
  "feat.finance.title": { en: "Financial Dashboard", ar: "لوحة المالية" },
  "feat.finance.desc": { en: "Track income, expenses, and generate monthly financial reports.", ar: "تتبع الإيرادات والمصروفات وإنشاء تقارير مالية شهرية." },
  "feat.realtime.title": { en: "Real-time Updates", ar: "تحديثات فورية" },
  "feat.realtime.desc": { en: "Instant updates across all devices — always see the latest clinic data.", ar: "تحديثات فورية على جميع الأجهزة — شاهد دائماً أحدث بيانات العيادة." },
  "feat.secure.title": { en: "Secure & Compliant", ar: "آمن ومتوافق" },
  "feat.secure.desc": { en: "Role-based access control for admins, secretaries and clinic staff.", ar: "تحكم في الوصول بحسب الدور للمدراء والسكرتيرة وموظفي العيادة." },
  "feat.bilingual.title": { en: "Arabic & English", ar: "عربي وإنجليزي" },
  "feat.bilingual.desc": { en: "Full support for both Arabic (RTL) and English language interfaces.", ar: "دعم كامل للغة العربية (RTL) وواجهات اللغة الإنجليزية." },
  // Pricing
  "pricing.title": { en: "Simple, Transparent Pricing", ar: "أسعار بسيطة وشفافة" },
  "pricing.subtitle": { en: "Start with a 15-day free trial. No credit card required.", ar: "ابدأ بتجربة مجانية 15 يوماً. لا حاجة لبطاقة ائتمانية." },
  "pricing.popular": { en: "Most Popular", ar: "الأكثر شيوعاً" },
  "pricing.basic.name": { en: "Basic Plan", ar: "الخطة الأساسية" },
  "pricing.basic.desc": { en: "Perfect for small clinics", ar: "مثالية للعيادات الصغيرة" },
  "pricing.premium.name": { en: "Premium Plan", ar: "الخطة المميزة" },
  "pricing.premium.desc": { en: "Full-featured for growing clinics", ar: "متكاملة للعيادات النامية" },
  "pricing.cta": { en: "Start Free Trial", ar: "ابدأ التجربة المجانية" },
  // How it works
  "how.title": { en: "How to Get Started with ClinicSquad?", ar: "كيف تبدأ مع كلينيك سكواد؟" },
  "how.subtitle": { en: "Four simple steps from sign-up to a fully running, data-driven clinic.", ar: "أربع خطوات بسيطة من التسجيل إلى عيادة متكاملة تعمل بالبيانات." },
  "how.step1.title": { en: "Create Your Account", ar: "أنشئ حسابك" },
  "how.step1.desc": { en: "Register in seconds — no credit card required. Set up your clinic profile with your name, specialty, and consultation fees.", ar: "سجّل في ثوانٍ — بدون بطاقة ائتمانية. أنشئ ملف عيادتك مع اسمك وتخصصك ورسوم الكشف." },
  "how.step2.title": { en: "Customize Your Settings", ar: "خصّص إعداداتك" },
  "how.step2.desc": { en: "Configure consultation fees, add doctors and secretary accounts, and personalize the system to match your daily workflow.", ar: "حدّد رسوم الكشف، أضف حسابات الأطباء والسكرتيرة، وخصّص النظام ليناسب سير عملك اليومي." },
  "how.step3.title": { en: "Add Patients & Book Appointments", ar: "أضف المرضى واحجز المواعيد" },
  "how.step3.desc": { en: "Start adding patient records and booking appointments. The system handles the waitlist, visit history, and billing automatically.", ar: "ابدأ بإضافة سجلات المرضى وحجز المواعيد. النظام يتولى قائمة الانتظار وسجل الزيارات والفواتير تلقائياً." },
  "how.step4.title": { en: "Track & Grow", ar: "تابع وانمُ" },
  "how.step4.desc": { en: "Monitor clinic performance, revenue trends, and patient statistics from a beautiful analytics dashboard.", ar: "تابع أداء عيادتك واتجاهات الإيرادات وإحصائيات المرضى من لوحة تحليلات أنيقة." },
  "test.title": { en: "Trusted by Egyptian Doctors", ar: "موثوق به من الأطباء المصريين" },
  // CTA Section
  "cta.title": { en: "Ready to Transform Your Clinic?", ar: "مستعد لتحويل عيادتك؟" },
  "cta.subtitle": { en: "Join hundreds of Egyptian clinics already using ClinicSquad to streamline their operations.", ar: "انضم لمئات العيادات المصرية التي تستخدم كلينيك سكواد لتبسيط عملياتها." },
  "cta.btn1": { en: "Start Free Trial — 15 Days", ar: "ابدأ التجربة المجانية — 15 يوماً" },
  "cta.btn2": { en: "Contact via WhatsApp", ar: "تواصل عبر واتساب" },
  
  // Auth Pages
  "auth.login.title": { en: "Welcome back", ar: "مرحباً بعودتك" },
  "auth.login.subtitle": { en: "Sign in to your clinic account", ar: "سجّل الدخول إلى حساب عيادتك" },
  "auth.login.email": { en: "Email", ar: "البريد الإلكتروني" },
  "auth.login.password": { en: "Password", ar: "كلمة المرور" },
  "auth.login.forgot": { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
  "auth.login.submit": { en: "Sign In", ar: "تسجيل الدخول" },
  "auth.login.noAccount": { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
  "auth.login.register": { en: "Register your clinic", ar: "سجّل عيادتك" },
  "auth.login.hero.title": { en: "The command center for your clinic", ar: "مركز القيادة لعيادتك" },
  "auth.login.hero.subtitle": { en: "Manage patients, appointments, and finances — all in one place, built for Egyptian clinics.", ar: "أدِر المرضى والمواعيد والمالية — كل ذلك في مكان واحد، مصمم للعيادات المصرية." },
  "auth.login.hero.feat1": { en: "Patient management", ar: "إدارة المرضى" },
  "auth.login.hero.feat2": { en: "Appointment scheduling", ar: "جدولة المواعيد" },
  "auth.login.hero.feat3": { en: "Financial tracking", ar: "تتبع المالية" },

  "auth.register.title": { en: "Start your free trial", ar: "ابدأ تجربتك المجانية" },
  "auth.register.subtitle": { en: "Join 500+ clinics using ClinicSquad to grow.", ar: "انضم لأكثر من 500 عيادة تستخدم كلينيك سكواد للنمو." },
  "auth.register.name": { en: "Clinic Name", ar: "اسم العيادة" },
  "auth.register.owner": { en: "Doctor Name", ar: "اسم الطبيب" },
  "auth.register.email": { en: "Work Email", ar: "بريد العمل" },
  "auth.register.password": { en: "Password", ar: "كلمة المرور" },
  "auth.register.submit": { en: "Create Clinic Account", ar: "إنشاء حساب العيادة" },
  "auth.register.haveAccount": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "auth.register.login": { en: "Sign in instead", ar: "سجّل الدخول بدلاً من ذلك" },
  "auth.register.hero.title": { en: "Request your free 15-day trial", ar: "اطلب تجربتك المجانية لمدة 15 يوماً" },
  "auth.register.hero.subtitle": { en: "Tell us about your clinic and our team will activate your trial within minutes.", ar: "أخبرنا عن عيادتك وسيقوم فريقنا بتفعيل تجربتك في غضون دقائق." },
  "auth.register.hero.feat1": { en: "Full access during trial", ar: "وصول كامل خلال فترة التجربة" },
  "auth.register.hero.feat2": { en: "Both Basic and Premium features", ar: "كل المميزات الأساسية والمتقدمة" },
  "auth.register.hero.feat3": { en: "Cancel anytime — no credit card", ar: "إلغاء في أي وقت — بدون بطاقة ائتمانية" },
  "auth.register.hero.trusted": { en: "Trusted by 500+ Egyptian clinics", ar: "موثوق به من أكثر من 500 عيادة مصرية" },
  "auth.register.specialty": { en: "Medical Specialty", ar: "التخصص الطبي" },
  "auth.register.whatsapp": { en: "WhatsApp Number", ar: "رقم الواتساب" },
  "auth.register.terms": { en: "By requesting a trial, you agree to our Terms of Service and Privacy Policy.", ar: "بطلبك للتجربة، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا." },

  // Dashboard sidebar
  "sidebar.clinic": { en: "Clinic", ar: "العيادة" },
  "sidebar.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "sidebar.patients": { en: "Patients", ar: "المرضى" },
  "sidebar.appointments": { en: "Appointments", ar: "المواعيد" },
  "sidebar.waitingList": { en: "Waiting List", ar: "قائمة الانتظار" },
  "sidebar.checkout": { en: "Checkout", ar: "الحساب" },
  "sidebar.insights": { en: "Insights", ar: "التحليلات" },
  "sidebar.finances": { en: "Finances", ar: "المالية" },
  "sidebar.settings": { en: "Settings", ar: "الإعدادات" },
  "sidebar.admin": { en: "Admin Panel", ar: "لوحة الإدارة" },
  "sidebar.platformFinances": { en: "Revenue", ar: "الإيرادات" },
  "sidebar.platformClinics": { en: "Clinics", ar: "العيادات" },
  "sidebar.platformPayments": { en: "Payments & Plans", ar: "المدفوعات والخطط" },
  "sidebar.platformSettings": { en: "Platform Settings", ar: "إعدادات المنصة" },
  "sidebar.platformGrowth": { en: "Growth Tools", ar: "أدوات النمو" },
  "sidebar.platformLogs": { en: "System Logs", ar: "سجلات النظام" },
  "sidebar.team": { en: "Team", ar: "الفريق" },
  "sidebar.prescriptions": { en: "ePrescription", ar: "الوصفة الإلكترونية" },
  "sidebar.subscription": { en: "Subscription", ar: "الاشتراك" },
  "sidebar.secure.title": { en: "Secure Access", ar: "الوصول الآمن" },
  "sidebar.signOut": { en: "Sign Out", ar: "تسجيل الخروج" },

  // Common
  "impersonation.viewingAs": { en: "You are viewing the clinic as", ar: "أنت تعرض العيادة بصفتك" },
  "impersonation.returnToAdmin": { en: "Return to Super Admin", ar: "العودة إلى المدير العام" },
  "common.trialLeft": { en: " days left in trial", ar: " أيام متبقية في التجربة" },
  "common.upgradePlan": { en: "Upgrade Plan", ar: "ترقية الخطة" },
  "common.upgrade": { en: "Upgrade Now", ar: "ترقية الآن" },
  "common.subExpired": { en: "Subscription Expired", ar: "انتهى الاشتراك" },
  "common.trialExpires": { en: "Trial expires in", ar: "تنتهي التجربة خلال" },
  "common.day": { en: "day", ar: "يوم" },
  "common.days": { en: "days", ar: "أيام" },
  "common.upgradeNow": { en: "Upgrade Now", ar: "ترقية الآن" },
  "common.all": { en: "All", ar: "الكل" },
  "common.cancel": { en: "Cancel", ar: "إلغاء" },
  "common.close": { en: "Close", ar: "إغلاق" },
  "dash.trial.days": { en: "days left in trial", ar: "أيام متبقية في التجربة" },
  "dash.trial.note": { en: "Your trial period will end soon. Upgrade to a paid plan to keep all features.", ar: "ستنتهي الفترة التجريبية قريبًا. قم بالترقية إلى خطة مدفوعة للحفاظ على جميع الميزات." },
  "dash.stats.patients": { en: "Patients", ar: "المرضى" },
  "dash.stats.appointments": { en: "Today's Appointments", ar: "مواعيد اليوم" },
  "dash.stats.revenue": { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  "dash.stats.expenses": { en: "Expenses", ar: "المصاريف" },
  "dash.stats.completed": { en: "Completed Sessions", ar: "الجلسات المكتملة" },
  "dash.stats.totalSessions": { en: "total sessions", ar: "إجمالي الجلسات" },
  "dash.stats.newMonth": { en: "new this month", ar: "جديد هذا الشهر" },
  "dash.stats.upcoming": { en: "upcoming", ar: "قادم" },
  "dash.schedule.today": { en: "Today's Schedule", ar: "جدول اليوم" },
  "dash.schedule.tomorrow": { en: "Tomorrow", ar: "غداً" },
  "dash.schedule.viewAll": { en: "View all appointments", ar: "عرض جميع المواعيد" },
  "dash.schedule.empty": { en: "No appointments for today", ar: "لا توجد مواعيد لليوم" },
  "dash.schedule.emptyTomorrow": { en: "No appointments for tomorrow", ar: "لا توجد مواعيد لغد" },
  "dash.schedule.book": { en: "Schedule appointment", ar: "حجز موعد" },
  "dash.schedule.upcoming": { en: "Upcoming schedule", ar: "الجدول القادم" },

  // Statuses
  "status.inProgress": { en: "In progress", ar: "قيد الكشف" },
  "status.waiting": { en: "Waiting", ar: "في الانتظار" },
  "status.completed": { en: "Completed", ar: "مكتمل" },
  "status.registered": { en: "Registered", ar: "مسجل" },
  "status.scheduled": { en: "Scheduled", ar: "مجدول" },
  "status.cancelled": { en: "Cancelled", ar: "ملغي" },
  "status.noShow": { en: "No Show", ar: "لم يحضر" },
  "status.checkedIn": { en: "Checked-in", ar: "تم الدخول" },
  "status.active": { en: "Active", ar: "نشط" },
  "status.pending": { en: "Pending", ar: "معلق" },
  "status.blocked": { en: "Deactivated", ar: "غير مفعلة" },
  "status.deactivated": { en: "Deactivated", ar: "غير مفعلة" },
  "status.patients": { en: "patients", ar: "مرضى" },

  // Prescriptions
  "presc.title": { en: "ePrescription", ar: "الوصفة الإلكترونية" },
  "presc.subtitle": { en: "Write, print, and send prescriptions to your patients.", ar: "اكتب واطبع وأرسل الوصفات الطبية لمرضاك." },
  "presc.new": { en: "New Prescription", ar: "وصفة جديدة" },
  "presc.cancel": { en: "Cancel", ar: "إلغاء" },
  "presc.selectPatient": { en: "Select a patient", ar: "اختر مريضاً" },
  "presc.addMedication": { en: "Add at least one medication", ar: "أضف دواءً واحداً على الأقل" },
  "presc.created": { en: "Prescription created", ar: "تم إنشاء الوصفة" },
  "presc.failed": { en: "Failed to create prescription", ar: "فشل إنشاء الوصفة" },
  "presc.confirmDelete": { en: "Delete this prescription?", ar: "حذف هذه الوصفة؟" },
  "presc.deleted": { en: "Deleted", ar: "تم الحذف" },
  "presc.failedDelete": { en: "Failed to delete", ar: "فشل الحذف" },
  "presc.patient": { en: "Patient", ar: "المريض" },
  "presc.selectPatientPh": { en: "Select patient", ar: "اختر المريض" },
  "presc.date": { en: "Date", ar: "التاريخ" },
  "presc.diagnosis": { en: "Diagnosis", ar: "التشخيص" },
  "presc.diagnosisPh": { en: "e.g. Acute pharyngitis", ar: "مثال: التهاب الحلق الحاد" },
  "presc.medications": { en: "Medications", ar: "الأدوية" },
  "presc.addMedBtn": { en: "Add medication", ar: "أضف دواء" },
  "presc.drugName": { en: "Drug name", ar: "اسم الدواء" },
  "presc.drugNamePh": { en: "e.g. Amoxicillin 500mg", ar: "مثال: أموكسيسيلين 500 مجم" },
  "presc.dosage": { en: "Dosage", ar: "الجرعة" },
  "presc.dosagePh": { en: "1 capsule", ar: "كبسولة واحدة" },
  "presc.frequency": { en: "Frequency", ar: "التكرار" },
  "presc.frequencyPh": { en: "3× daily", ar: "3 مرات يومياً" },
  "presc.duration": { en: "Duration", ar: "المدة" },
  "presc.durationPh": { en: "7 days", ar: "7 أيام" },
  "presc.clinicalNotes": { en: "Clinical Notes", ar: "ملاحظات سريرية" },
  "presc.clinicalNotesPh": { en: "e.g. Take after meals, complete the course", ar: "مثال: تؤخذ بعد الوجبات، أكمل الجرعة" },
  "presc.save": { en: "Save Prescription", ar: "حفظ الوصفة" },
  "presc.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "presc.empty": { en: "No prescriptions found", ar: "لم يتم العثور على وصفات" },
  "presc.searchPh": { en: "Search by patient, diagnosis, or drug name", ar: "البحث بالمريض أو التشخيص أو اسم الدواء" },
  "presc.delete": { en: "Delete", ar: "حذف" },
  "presc.view": { en: "View", ar: "عرض" },
  "presc.preview": { en: "Live preview", ar: "معاينة مباشرة" },

  // Dashboard
  "dash.title": { en: "Dashboard", ar: "لوحة التحكم" },
  "dash.stats.totalPatients": { en: "Total Patients", ar: "إجمالي المرضى" },
  "dash.stats.newThisMonth": { en: "new this month", ar: "جديد هذا الشهر" },
  "dash.stats.todayAppts": { en: "Today's Appointments", ar: "مواعيد اليوم" },
  "dash.stats.total": { en: "total sessions", ar: "إجمالي الجلسات" },
  "dash.today.title": { en: "Today's Schedule", ar: "جدول اليوم" },
  "dash.today.viewAll": { en: "View all appointments", ar: "عرض كل المواعيد" },
  "dash.today.empty": { en: "No appointments for today", ar: "لا توجد مواعيد اليوم" },
  "dash.today.schedule": { en: "Schedule appointment", ar: "جدولة موعد" },
  "dash.tomorrow.title": { en: "Tomorrow", ar: "غداً" },
  "dash.tomorrow.subtitle": { en: "Upcoming schedule", ar: "الجدول القادم" },
  "dash.tomorrow.empty": { en: "No appointments for tomorrow", ar: "لا توجد مواعيد لغد" },
  "dash.stats.waiting": { en: "In Waiting List", ar: "في قائمة الانتظار" },
  "dash.stats.activeTrial": { en: "Active Trial", ar: "تجربة نشطة" },
  "dash.stats.daysLeft": { en: "days left", ar: "أيام متبقية" },
  "dash.recentAppts": { en: "Recent Appointments", ar: "المواعيد الأخيرة" },
  "dash.viewAll": { en: "View All", ar: "عرض الكل" },
  "dash.noAppts": { en: "No appointments today", ar: "لا توجد مواعيد اليوم" },
  "dash.revenueOverview": { en: "Revenue Overview", ar: "نظرة عامة على الإيرادات" },

  // Patients
  "patients.title": { en: "Patients", ar: "المرضى" },
  "patients.subtitle": { en: "Manage your patient records and medical history.", ar: "أدِر سجلات مرضاك وتاريخهم الطبي." },
  "patients.new": { en: "New Patient", ar: "مريض جديد" },
  "patients.add": { en: "Add Patient", ar: "أضف مريضاً" },
  "patients.onFile": { en: "patients on file", ar: "مريض مسجل" },
  "patients.searchPh": { en: "Search patients (PT-0001, name, phone)...", ar: "البحث عن المرضى (PT-0001، الاسم، الهاتف)..." },
  "patients.id": { en: "ID", ar: "المعرف" },
  "patients.name": { en: "Name", ar: "الاسم" },
  "patients.age": { en: "Age", ar: "السن" },
  "patients.phone": { en: "Phone", ar: "الهاتف" },
  "patients.visitType": { en: "Visit Type", ar: "نوع الزيارة" },
  "patients.visitType.newConsultation": { en: "New Consultation", ar: "كشف جديد" },
  "patients.visitType.followUp": { en: "Follow-up", ar: "متابعة" },
  "patients.visitType.reExam": { en: "Re-exam", ar: "إعادة كشف" },
  "patients.visitType.emergency": { en: "Emergency", ar: "طوارئ" },
  "patients.visitType.unspecified": { en: "Unspecified", ar: "غير محدد" },
  "patients.status": { en: "Status", ar: "الحالة" },
  "patients.dateAdded": { en: "Date Added", ar: "تاريخ الإضافة" },
  "patients.actions": { en: "Actions", ar: "الإجراءات" },
  "patients.selectAll": { en: "Select all visible patients", ar: "تحديد جميع المرضى الظاهرين" },
  "patients.selectPatient": { en: "Select patient", ar: "تحديد المريض" },
  "patients.selected": { en: "patients selected", ar: "مرضى محددون" },
  "patients.clearSelection": { en: "Clear selection", ar: "مسح التحديد" },
  "patients.exportSelected": { en: "Export selected", ar: "تصدير المحدد" },
  "patients.bulkCheckIn": { en: "Bulk check-in", ar: "تسجيل دخول جماعي" },
  "patients.paymentRequired": { en: "Payment required", ar: "الدفع مطلوب" },
  "patients.noPaidSelected": { en: "Select at least one paid patient", ar: "حدد مريضاً واحداً على الأقل تم دفعه" },
  "patients.skipped": { en: "skipped", ar: "تم تخطيهم" },
  "patients.confirmBulkCheckIn": { en: "Send the selected patients to the waiting list?", ar: "هل تريد إرسال المرضى المحددين إلى قائمة الانتظار؟" },
  "patients.bulkCheckInDialog.title": { en: "Bulk check-in", ar: "تسجيل دخول جماعي" },
  "patients.bulkCheckInDialog.desc": { en: "Choose one Visit Type for the selected patients before sending them to the waiting list.", ar: "اختر نوع زيارة واحداً للمرضى المحددين قبل إرسالهم إلى قائمة الانتظار." },
  "patients.toast.exported": { en: "Selected patients exported", ar: "تم تصدير المرضى المحددين" },
  "patients.toast.bulkCheckedIn": { en: "Patients sent to waiting list", ar: "تم إرسال المرضى إلى قائمة الانتظار" },
  "patients.toast.bulkCheckInFailed": { en: "Bulk check-in failed", ar: "فشل التسجيل الجماعي" },
  "patients.notFound": { en: "No patients found", ar: "لم يتم العثور على مرضى" },
  "patients.empty": { en: "No patients yet", ar: "لا يوجد مرضى بعد" },
  "patients.addFirst": { en: "Add your first patient to get started", ar: "أضف أول مريض للبدء" },
  "patients.toast.created": { en: "Patient created successfully", ar: "تم إنشاء المريض بنجاح" },
  "patients.toast.failed": { en: "Failed to create patient", ar: "فشل إنشاء المريض" },
  "patients.toast.sentToQueue": { en: "sent to waiting list", ar: "تم إرساله لقائمة الانتظار" },
  "patients.toast.checkInFailed": { en: "Failed to check in", ar: "فشل الدخول" },
  "patients.checkIn": { en: "Check-in", ar: "دخول" },
  "patients.checkInDialog.title": { en: "Check-in Patient", ar: "تسجيل دخول المريض" },
  "patients.checkInDialog.desc": { en: "Select visit type and send patient to the doctor's waiting list.", ar: "اختر نوع الزيارة وأرسل المريض إلى قائمة انتظار الطبيب." },
  "patients.sendToDoctor": { en: "Send to Doctor", ar: "إرسال إلى الطبيب" },
  "patients.addDialog.title": { en: "Add Patient", ar: "إضافة مريض" },
  "patients.addDialog.desc": { en: "Register the patient and add them to the doctor's queue in one step.", ar: "سجّل المريض وأضفه إلى قائمة انتظار الطبيب في خطوة واحدة." },
  "patients.addDialog.profileDesc": { en: "Save the patient profile now and schedule their visit later.", ar: "احفظ ملف المريض الآن وحدد موعد الزيارة لاحقاً." },
  "patients.queueImmediately": { en: "Add to today's waiting queue immediately", ar: "إضافة إلى قائمة انتظار اليوم فوراً" },
  "patients.queueImmediatelyHint": { en: "Checked by default for fast walk-ins. Turn it off to save this patient for later scheduling.", ar: "محدد افتراضياً للمرضى الحاضرين سريعاً. ألغِ التحديد لحفظ المريض لجدولة موعد لاحقاً." },
  "patients.doctor": { en: "Doctor", ar: "الطبيب" },
  "patients.selectDoctor": { en: "Select doctor", ar: "اختر الطبيب" },
  "patients.consultationPrice": { en: "Consultation price", ar: "سعر الكشف" },
  "patients.cashCollected": { en: "Cash collected", ar: "تم تحصيل النقد" },
  "patients.cashCollectedHint": { en: "Checked by default for standard cash visits.", ar: "محدد افتراضياً للزيارات النقدية المعتادة." },
  "patients.paymentException": { en: "Exception status", ar: "حالة الاستثناء" },
  "patients.freeVisit": { en: "Free consultation", ar: "كشف مجاني" },
  "patients.unpaidVisit": { en: "Unpaid / collect later", ar: "غير مدفوع / التحصيل لاحقاً" },
  "patients.addToQueue": { en: "Add to Queue", ar: "إضافة إلى قائمة الانتظار" },
  "patients.queueAdded": { en: "Patient added to the waiting list", ar: "تمت إضافة المريض إلى قائمة الانتظار" },
  "patients.fullName": { en: "Full Name", ar: "الاسم الكامل" },
  "patients.bloodType": { en: "Blood Type", ar: "فصيلة الدم" },
  "patients.allergies": { en: "Allergies", ar: "الحساسية" },
  "patients.clinicalNotes": { en: "Clinical Notes", ar: "ملاحظات سريرية" },
  "patients.save": { en: "Save Patient", ar: "حفظ المريض" },
  "patients.toast.addFailed": { en: "Failed to add patient", ar: "فشل إضافة المريض" },
  "patients.toast.savedForLater": { en: "Patient profile saved for later scheduling", ar: "تم حفظ ملف المريض لجدولة موعد لاحقاً" },

  // Waiting List
  "waiting.title": { en: "Waiting List", ar: "قائمة الانتظار" },
  "waiting.subtitle": { en: "Manage patients currently waiting for their consultation.", ar: "أدِر المرضى الذين ينتظرون كشفهم حالياً." },
  "waiting.count": { en: "patient waiting", ar: "مريض في الانتظار" },
  "waiting.countPlural": { en: "patients waiting", ar: "مرضى في الانتظار" },
  "waiting.empty": { en: "Waiting list is empty", ar: "قائمة الانتظار فارغة" },
  "waiting.emptyDesc": { en: "Checked-in patients will appear here.", ar: "سيظهر هنا المرضى الذين تم تسجيل دخولهم." },
  "waiting.callNext": { en: "Call Next Patient", ar: "نداء المريض التالي" },
  "waiting.patient": { en: "Patient", ar: "المريض" },
  "waiting.time": { en: "Wait Time", ar: "وقت الانتظار" },
  "waiting.type": { en: "Type", ar: "النوع" },
  "waiting.actions": { en: "Actions", ar: "الإجراءات" },
  "waiting.action": { en: "Action", ar: "الإجراء" },
  "waiting.start": { en: "Start Session", ar: "بدء الجلسة" },
  "waiting.open": { en: "Open Patient", ar: "فتح ملف المريض" },
  "waiting.doctorOnly": { en: "Doctor starts session", ar: "الطبيب يبدأ الجلسة" },
  "waiting.failedOpen": { en: "Could not open patient", ar: "تعذر فتح ملف المريض" },
  "waiting.remove": { en: "Remove", ar: "إزالة" },
  "waiting.paid": { en: "Paid", ar: "مدفوع" },
  "waiting.free": { en: "Free visit", ar: "زيارة مجانية" },
  "waiting.unpaid": { en: "Unpaid", ar: "غير مدفوع" },

  // Checkout
  "checkout.title": { en: "Payment & Checkout", ar: "الدفع وإتمام الزيارة" },
  "checkout.subtitle": { en: "Record or review patient payments and complete visits.", ar: "سجّل أو راجع مدفوعات المرضى وأتمم الزيارات." },
  "checkout.empty": { en: "No patients awaiting payment", ar: "لا يوجد مرضى بانتظار الدفع" },
  "checkout.paid": { en: "Paid", ar: "تم الدفع" },
  "checkout.markPaid": { en: "Mark Paid", ar: "تسجيل الدفع" },
  "checkout.sendToQueue": { en: "Send to Waiting List", ar: "إرسال إلى قائمة الانتظار" },
  "checkout.queueReady": { en: "Paid and ready for queue", ar: "تم الدفع وجاهز لقائمة الانتظار" },
  "checkout.patient": { en: "Patient", ar: "المريض" },
  "checkout.amount": { en: "Amount", ar: "المبلغ" },
  "checkout.status": { en: "Status", ar: "الحالة" },
  "checkout.actions": { en: "Actions", ar: "الإجراءات" },
  "checkout.process": { en: "Process Payment", ar: "دفع الحساب" },
  "checkout.complete": { en: "Complete Session", ar: "إتمام الجلسة" },
  "checkout.confirmQueue": { en: "Send this paid patient to the waiting list?", ar: "هل تريد إرسال هذا المريض الذي دفع إلى قائمة الانتظار؟" },
  "checkout.toast.paid": { en: "payment recorded", ar: "تم تسجيل الدفع" },
  "checkout.toast.queued": { en: "is ready in the waiting list", ar: "أصبح جاهزاً في قائمة الانتظار" },
  "checkout.emptyDesc": { en: "Newly registered patients will appear here until payment is recorded.", ar: "سيظهر المرضى المسجلون حديثاً هنا حتى يتم تسجيل الدفع." },
  "checkout.totalDue": { en: "Today's expected total", ar: "إجمالي المتوقع اليوم" },
  "checkout.patientReady": { en: "patient ready for payment", ar: "مريض جاهز للدفع" },
  "checkout.patientsReady": { en: "patients ready for payment", ar: "مرضى جاهزون للدفع" },
  "checkout.processSummary": { en: "Process payments and complete active patient sessions.", ar: "عالج المدفوعات وأكمل جلسات المرضى النشطة." },
  "checkout.amountDue": { en: "Amount", ar: "المبلغ" },
  "checkout.setInSettings": { en: "Set a visit price", ar: "حدد سعر الزيارة" },
  "checkout.requeue": { en: "Send to queue", ar: "إرسال للقائمة" },
  "checkout.paymentDialog.title": { en: "Record pre-session payment", ar: "تسجيل الدفع قبل الجلسة" },
  "checkout.paymentDialog.desc": { en: "Choose how the patient paid. The patient can enter the waiting list only after payment is recorded.", ar: "اختر طريقة دفع المريض. لا يمكن إدخال المريض إلى قائمة الانتظار إلا بعد تسجيل الدفع." },
  "checkout.paymentMethod": { en: "Payment method", ar: "طريقة الدفع" },
  "checkout.cashHint": { en: "Cash is selected by default for the most common clinic payment workflow.", ar: "تم اختيار الدفع النقدي افتراضياً لأنه الأكثر شيوعاً في العيادات." },
  "checkout.method.cash": { en: "Cash", ar: "نقدي" },
  "checkout.method.vodafone_cash": { en: "Vodafone Cash", ar: "فودافون كاش" },
  "checkout.method.instapay": { en: "InstaPay", ar: "إنستاباي" },
  "checkout.method.card": { en: "Bank card", ar: "بطاقة بنكية" },
  "checkout.method.other": { en: "Other", ar: "أخرى" },
  "checkout.reference": { en: "Reference or note", ar: "المرجع أو ملاحظة" },
  "checkout.referencePlaceholder": { en: "Transaction reference, wallet name, or short note", ar: "رقم العملية أو اسم المحفظة أو ملاحظة قصيرة" },
  "checkout.referenceHint": { en: "Optional, but recommended for Vodafone Cash and InstaPay payments.", ar: "اختياري، لكن يفضل مع مدفوعات فودافون كاش وإنستاباي." },
  "checkout.confirmPayment": { en: "Record payment", ar: "تسجيل الدفع" },
  "checkout.receiptTitle": { en: "Payment receipt", ar: "إيصال الدفع" },
  "checkout.receiptSaved": { en: "Payment recorded. The patient is now eligible for the waiting list.", ar: "تم تسجيل الدفع. أصبح المريض الآن مؤهلاً لقائمة الانتظار." },
  "checkout.receivedAt": { en: "Received at", ar: "وقت الاستلام" },
  "checkout.printReceipt": { en: "Print receipt", ar: "طباعة الإيصال" },
  "checkout.receiptFooter": { en: "Payment received before the clinical session.", ar: "تم استلام الدفع قبل الجلسة الطبية." },
  "checkout.toast.printBlocked": { en: "Please allow pop-ups to print the receipt.", ar: "يرجى السماح بالنوافذ المنبثقة لطباعة الإيصال." },

  // Finances
  "fin.title": { en: "Finances", ar: "المالية" },
  "fin.subtitle": { en: "Track your clinic's financial performance and transactions.", ar: "تتبع الأداء المالي لعيادتك والمعاملات." },
  "fin.stats.income": { en: "Total Income", ar: "إجمالي الدخل" },
  "fin.stats.expenses": { en: "Total Expenses", ar: "إجمالي المصروفات" },
  "fin.stats.net": { en: "Net Profit", ar: "صافي الربح" },
  "fin.transactions.title": { en: "Recent Transactions", ar: "المعاملات الأخيرة" },
  "fin.transactions.empty": { en: "No transactions found", ar: "لم يتم العثور على معاملات" },
  "fin.transactions.date": { en: "Date", ar: "التاريخ" },
  "fin.transactions.desc": { en: "Description", ar: "الوصف" },
  "fin.transactions.amount": { en: "Amount", ar: "المبلغ" },
  "fin.transactions.type": { en: "Type", ar: "النوع" },
  "fin.type.income": { en: "Income", ar: "دخل" },
  "fin.type.expense": { en: "Expense", ar: "مصروف" },

  // Finance dashboard aliases
  "finances.title": { en: "Finances", ar: "المالية" },
  "finances.overview": { en: "Track clinic income, expenses, and profit.", ar: "تتبع دخل العيادة ومصروفاتها وأرباحها." },
  "finances.add": { en: "Add Transaction", ar: "إضافة معاملة" },
  "finances.income": { en: "Income", ar: "الدخل" },
  "finances.expenses": { en: "Expenses", ar: "المصروفات" },
  "finances.profit": { en: "Profit", ar: "الربح" },
  "finances.chartTitle": { en: "Income and expenses", ar: "الدخل والمصروفات" },
  "finances.cashShiftTitle": { en: "Today's cash shift", ar: "الوردية النقدية اليوم" },
  "finances.cashShiftDate": { en: "Shift date:", ar: "تاريخ الوردية:" },
  "finances.cashPaid": { en: "Paid visits", ar: "الزيارات المدفوعة" },
  "finances.cashFree": { en: "Free visits", ar: "الزيارات المجانية" },
  "finances.cashUnpaid": { en: "Unpaid visits", ar: "الزيارات غير المدفوعة" },
  "finances.cashTransactions": { en: "Transactions", ar: "المعاملات" },
  "finances.type": { en: "Type", ar: "النوع" },
  "finances.description": { en: "Description", ar: "الوصف" },
  "finances.category": { en: "Category", ar: "الفئة" },
  "finances.date": { en: "Date", ar: "التاريخ" },
  "finances.amount": { en: "Amount", ar: "المبلغ" },
  "finances.empty": { en: "No financial transactions yet", ar: "لا توجد معاملات مالية بعد" },
  "finances.incomeLabel": { en: "Income", ar: "دخل" },
  "finances.expenseLabel": { en: "Expense", ar: "مصروف" },
  "finances.addDialog.title": { en: "Add Transaction", ar: "إضافة معاملة" },

  // Appointments
  "appt.title": { en: "Appointments", ar: "المواعيد" },
  "appt.subtitle": { en: "Manage your clinic's schedule and bookings.", ar: "أدِر جدول عيادتك والحجوزات." },
  "appt.new": { en: "New Appointment", ar: "موعد جديد" },
  "appt.calendar": { en: "Calendar View", ar: "عرض التقويم" },
  "appt.list": { en: "List View", ar: "عرض القائمة" },
  "appt.empty": { en: "No appointments scheduled", ar: "لا توجد مواعيد مجدولة" },
  "appt.date": { en: "Date", ar: "التاريخ" },
  "appt.time": { en: "Time", ar: "الوقت" },
  "appt.patient": { en: "Patient", ar: "المريض" },
  "appt.type": { en: "Type", ar: "النوع" },
  "appt.status": { en: "Status", ar: "الحالة" },
  "appt.actions": { en: "Actions", ar: "الإجراءات" },
  "appt.today": { en: "Today", ar: "اليوم" },
  "appt.scheduleAt": { en: "Schedule at", ar: "جدولة في" },
  "appt.viewDay": { en: "View day", ar: "عرض اليوم" },
  "appt.viewList": { en: "View list", ar: "عرض القائمة" },
  "appt.appointment": { en: "appointment", ar: "موعد" },
  "appt.appointments": { en: "appointments", ar: "مواعيد" },

  // Pending Activation
  "pending.title": { en: "Account Pending Activation", ar: "الحساب في انتظار التفعيل" },
  "pending.subtitle": { en: "Your clinic trial is being processed.", ar: "جاري معالجة فترة تجربة عيادتك." },
  "pending.msg": { en: "Our team is reviewing your registration. Your account will be activated shortly.", ar: "يقوم فريقنا بمراجعة تسجيلك. سيتم تفعيل حسابك قريباً." },
  "pending.whatsapp": { en: "Contact support via WhatsApp", ar: "تواصل مع الدعم عبر واتساب" },
  "pending.logout": { en: "Sign Out", ar: "تسجيل الخروج" },

  // Team
  "team.title": { en: "Team Management", ar: "إدارة الفريق" },
  "team.subtitle": { en: "Manage your clinic staff and their access roles.", ar: "أدِر موظفي عيادتك وأدوار وصولهم." },
  "team.plan.premium": { en: "Premium Plan", ar: "الخطة المميزة" },
  "team.plan.trial": { en: "Free Trial", ar: "تجربة مجانية" },
  "team.plan.basic": { en: "Basic Plan", ar: "الخطة الأساسية" },
  "team.plan.expired": { en: "Plan Expired", ar: "انتهت الخطة" },
  "team.capacity.title": { en: "Team Capacity", ar: "سعة الفريق" },
  "team.capacity.note.prefix": { en: "Your", ar: "خطتك" },
  "team.capacity.note.suffix": { en: "allows up to", ar: "تسمح بحد أقصى" },
  "team.capacity.members": { en: "team members", ar: "أعضاء فريق" },
  "team.capacity.upgrade": { en: "Upgrade for more slots", ar: "رقي للحصول على المزيد" },
  "team.invite.title": { en: "Invite Member", ar: "دعوة عضو" },
  "team.invite.limitMsg": { en: "You have reached your team member limit. Upgrade to invite more.", ar: "لقد وصلت إلى الحد الأقصى لأعضاء الفريق. رقي لدعوة المزيد." },
  "team.invite.name": { en: "Name", ar: "الاسم" },
  "team.invite.namePh": { en: "Full name", ar: "الاسم الكامل" },
  "team.invite.email": { en: "Email", ar: "البريد الإلكتروني" },
  "team.invite.role": { en: "Role", ar: "الدور" },
  "team.role.secretary": { en: "Secretary", ar: "سكرتارية" },
  "team.role.nurse": { en: "Nurse", ar: "تمريض" },
  "team.role.assistant": { en: "Assistant", ar: "مساعد" },
  "team.role.doctor": { en: "Doctor", ar: "طبيب" },
  "team.role.admin": { en: "Admin", ar: "مدير" },
  "team.role.you": { en: "You", ar: "أنت" },
  "team.role.owner": { en: "Owner", ar: "المالك" },
  "team.invite.send": { en: "Send Invite", ar: "إرسال الدعوة" },
  "team.pending.title": { en: "Pending Invitations", ar: "دعوات معلقة" },
  "team.pending.empty": { en: "No pending invitations", ar: "لا توجد دعوات معلقة" },
  "team.copied": { en: "Copied", ar: "تم النسخ" },
  "team.copyLink": { en: "Copy Link", ar: "نسخ الرابط" },
  "team.members.title": { en: "Active Members", ar: "الأعضاء النشطون" },
  "team.toast.inviteCreated": { en: "Invitation sent successfully", ar: "تم إرسال الدعوة بنجاح" },
  "team.toast.limitReached": { en: "Team limit reached", ar: "تم الوصول لحد الفريق" },
  "team.toast.duplicate": { en: "Email already invited", ar: "تمت دعوة هذا البريد مسبقاً" },
  "team.toast.failed": { en: "Failed to send invitation", ar: "فشل إرسال الدعوة" },
  "team.toast.failedTitle": { en: "Error", ar: "خطأ" },
  "team.toast.revoked": { en: "Invitation revoked", ar: "تم إلغاء الدعوة" },
  "team.confirm.remove": { en: "Are you sure you want to remove this member?", ar: "هل أنت متأكد من إزالة هذا العضو؟" },
  "team.toast.removed": { en: "Member removed", ar: "تم إزالة العضو" },
  "team.toast.copied": { en: "Link copied to clipboard", ar: "تم نسخ الرابط" },
  "team.toast.copyFailed": { en: "Failed to copy link", ar: "فشل نسخ الرابط" },

  // Settings
  "settings.title": { en: "Settings", ar: "الإعدادات" },
  "settings.profile.title": { en: "Profile", ar: "الملف الشخصي" },
  "settings.profile.specialty": { en: "Medical Specialty", ar: "التخصص الطبي" },
  "settings.profile.specialtyDesc": { en: "Shown on every prescription you issue (e.g. Cardiology, Pediatrics, Internal Medicine).", ar: "يظهر في كل وصفة طبية تصدرها (مثل: القلب، الأطفال، الباطنة)." },
  "settings.profile.specialtyPh": { en: "e.g. General Practitioner", ar: "مثال: ممارس عام" },
  "settings.profile.save": { en: "Save", ar: "حفظ" },
  "settings.profile.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "settings.profile.updated": { en: "Specialty updated", ar: "تم تحديث التخصص" },
  "settings.clinic.title": { en: "Clinic Identity", ar: "هوية العيادة" },
  "settings.clinic.desc": { en: "Shown on every prescription header and footer (PDF, print, and WhatsApp).", ar: "تظهر في رأس وتذييل كل وصفة طبية (PDF، طباعة، واتساب)." },
  "settings.clinic.name": { en: "Clinic Name *", ar: "اسم العيادة *" },
  "settings.clinic.namePh": { en: "e.g. ClinicSquad Medical Center", ar: "مثال: مركز كلينيك سكواد الطبي" },
  "settings.clinic.phone": { en: "Phone", ar: "الهاتف" },
  "settings.clinic.phonePh": { en: "e.g. +20 123 456 7890", ar: "مثال: 01234567890" },
  "settings.clinic.address": { en: "Address", ar: "العنوان" },
  "settings.clinic.addressPh": { en: "Street, City, Country", ar: "الشارع، المدينة، الدولة" },
  "settings.clinic.save": { en: "Save Identity", ar: "حفظ الهوية" },
  "settings.clinic.updated": { en: "Clinic identity updated", ar: "تم تحديث هوية العيادة" },
  "settings.info.title": { en: "Clinic Information", ar: "معلومات العيادة" },
  "settings.info.name": { en: "Clinic Name", ar: "اسم العيادة" },
  "settings.info.status": { en: "Account Status", ar: "حالة الحساب" },
  "settings.info.sub": { en: "Subscription", ar: "الاشتراك" },
  "settings.info.trialEnds": { en: "Trial Ends", ar: "تنتهي التجربة" },
  "settings.info.registered": { en: "Registered", ar: "تاريخ التسجيل" },
  "settings.pw.title": { en: "Change Password", ar: "تغيير كلمة المرور" },
  "settings.pw.current": { en: "Current Password", ar: "كلمة المرور الحالية" },
  "settings.pw.new": { en: "New Password", ar: "كلمة المرور الجديدة" },
  "settings.pw.confirm": { en: "Confirm New Password", ar: "تأكيد كلمة المرور" },
  "settings.pw.change": { en: "Change Password", ar: "تغيير كلمة المرور" },
  "settings.pw.changing": { en: "Changing...", ar: "جاري التغيير..." },
  "settings.pw.changed": { en: "Password changed successfully", ar: "تم تغيير كلمة المرور بنجاح" },
  "settings.security.title": { en: "Security Log", ar: "سجل الأمان" },
  "settings.security.desc": { en: "Recent account activity and sign-in events.", ar: "نشاط الحساب الأخير وأحداث تسجيل الدخول." },
  "settings.security.empty": { en: "No activity recorded yet", ar: "لا يوجد نشاط مسجل بعد" },
  "settings.toast.failed": { en: "Failed to update", ar: "فشل التحديث" },
  "settings.toast.pwFailed": { en: "Couldn't change password", ar: "لم نتمكن من تغيير كلمة المرور" },
  "settings.toast.pwIncorrect": { en: "Your current password is incorrect.", ar: "كلمة المرور الحالية غير صحيحة." },
  "settings.toast.pwRetry": { en: "Please double-check your input and try again.", ar: "يرجى التحقق من مدخلاتك والمحاولة مرة أخرى." },
  "settings.toast.clinicNameReq": { en: "Clinic name is required", ar: "اسم العيادة مطلوب" },
  "settings.toast.clinicFailed": { en: "Failed to update clinic", ar: "فشل تحديث العيادة" },

  // Insights
  "insights.title": { en: "Insights & Analytics", ar: "التحليلات والبيانات" },
  "insights.subtitle": { en: "Detailed overview of your clinic's performance and patient trends.", ar: "نظرة مفصلة على أداء عيادتك واتجاهات المرضى." },
  "insights.premium.title": { en: "Premium Analytics", ar: "تحليلات مميزة" },
  "insights.premium.desc": { en: "Upgrade to Premium to unlock detailed insights, revenue charts, and patient growth trends.", ar: "رقي إلى الخطة المميزة لفتح التحليلات المفصلة ورسوم الإيرادات واتجاهات نمو المرضى." },
  "insights.premium.upgrade": { en: "Upgrade to Premium", ar: "الترقية للمميزة" },
  "insights.metric.patients": { en: "Total Patients", ar: "إجمالي المرضى" },
  "insights.metric.newPatients": { en: "new patients", ar: "مرضى جدد" },
  "insights.metric.completion": { en: "Completion Rate", ar: "معدل الإتمام" },
  "insights.metric.completedOf": { en: "completed of", ar: "مكتمل من" },
  "insights.metric.revenue": { en: "Monthly Revenue", ar: "الإيرادات الشهرية" },
  "insights.metric.expenses": { en: "expenses", ar: "مصروفات" },
  "insights.metric.upcoming": { en: "Upcoming", ar: "قادم" },
  "insights.metric.today": { en: "today", ar: "اليوم" },
  "insights.metric.clinics": { en: "Clinics", ar: "العيادات" },
  "insights.metric.users": { en: "Users", ar: "المستخدمين" },
  "insights.busiest.dayTitle": { en: "Busiest Day This Month", ar: "اليوم الأكثر ازدحاماً هذا الشهر" },
  "insights.busiest.dayPeak": { en: "Peak activity", ar: "ذروة النشاط" },
  "insights.busiest.weekdayTitle": { en: "Most Active Weekday", ar: "اليوم الأكثر نشاطاً في الأسبوع" },
  "insights.busiest.weekdayHist": { en: "Historical average", ar: "المعدل التاريخي" },
  "insights.chart.appointmentsTitle": { en: "Appointment Volume", ar: "حجم المواعيد" },
  "insights.chart.appointmentsSub": { en: "Daily breakdown of consultations", ar: "توزيع يومي للاستشارات" },
  "insights.chart.statusTitle": { en: "Status Breakdown", ar: "توزيع الحالات" },
  "insights.chart.statusSub": { en: "All-time appointment outcomes", ar: "نتائج المواعيد طوال الوقت" },
  "insights.chart.weekdayTitle": { en: "Weekday Distribution", ar: "التوزيع حسب أيام الأسبوع" },
  "insights.chart.weekdaySub": { en: "Average patient flow by day", ar: "متوسط تدفق المرضى حسب اليوم" },
  "insights.chart.financeTitle": { en: "Financial Performance", ar: "الأداء المالي" },
  "insights.chart.financeSub": { en: "Monthly income vs expenses", ar: "الدخل الشهري مقابل المصروفات" },
  "insights.chart.income": { en: "Income", ar: "الدخل" },
  "insights.chart.expense": { en: "Expense", ar: "المصروف" },
  "insights.chart.profit": { en: "Net Profit", ar: "صافي الربح" },

  // Admin
  "admin.title": { en: "Platform Admin", ar: "إدارة المنصة" },
  "admin.subtitle": { en: "Overview of all clinics, subscriptions, and platform activity", ar: "نظرة عامة على جميع العيادات والاشتراكات ونشاط المنصة" },
  "admin.metric.newSignups": { en: "New Signups", ar: "تسجيلات جديدة" },
  "admin.metric.trialEnding": { en: "Trial Ending", ar: "تجربة تنتهي" },
  "admin.metric.pendingPayments": { en: "Pending Payments", ar: "مدفوعات معلقة" },
  "admin.metric.confirmedRevenue": { en: "Confirmed Revenue", ar: "إيرادات مؤكدة" },
  "admin.pending.title": { en: "Pending Approvals", ar: "الموافقات المعلقة" },
  "admin.pending.waiting": { en: "waiting", ar: "في الانتظار" },
  "admin.pending.empty": { en: "No clinics pending approval", ar: "لا توجد عيادات في انتظار الموافقة" },
  "admin.pending.joined": { en: "Joined", ar: "انضم" },
  "admin.pending.activate": { en: "Activate Trial", ar: "تفعيل التجربة" },
  "admin.plans.title": { en: "Subscribers by Plan", ar: "المشتركون حسب الخطة" },
  "admin.payments.title": { en: "Payment Confirmations", ar: "تأكيدات الدفع" },
  "admin.payments.pending": { en: "pending", ar: "معلق" },
  "admin.payments.empty": { en: "No pending payment confirmations", ar: "لا توجد تأكيدات دفع معلقة" },
  "admin.payments.confirm": { en: "Confirm", ar: "تأكيد" },
  "admin.history.title": { en: "Recent Platform Activity", ar: "نشاط المنصة الأخير" },
  "admin.history.empty": { en: "No recent activity", ar: "لا يوجد نشاط أخير" },
  "admin.clinics.title": { en: "All Clinics", ar: "كل العيادات" },
  "admin.clinics.searchPh": { en: "Search clinics...", ar: "البحث عن العيادات..." },
  "admin.clinics.name": { en: "Clinic Name", ar: "اسم العيادة" },
  "admin.clinics.owner": { en: "Owner", ar: "المالك" },
  "admin.clinics.status": { en: "Status", ar: "الحالة" },
  "admin.clinics.sub": { en: "Subscription", ar: "الاشتراك" },
  "admin.clinics.joined": { en: "Joined", ar: "انضم في" },
  "admin.clinics.actions": { en: "Actions", ar: "الإجراءات" },
  "admin.clinics.block": { en: "Block", ar: "حظر" },
  "admin.clinics.blocked": { en: "Blocked", ar: "محظور" },
  "admin.clinics.active": { en: "Active", ar: "نشط" },
  "admin.clinics.pending": { en: "Pending", ar: "معلق" },

  // Plans
  "plan.trial": { en: "Trial", ar: "تجربة" },
  "plan.basic": { en: "Basic", ar: "أساسي" },
  "plan.premium": { en: "Premium", ar: "مميز" },
  "plan.trial.desc": { en: "15-day evaluation", ar: "تقييم لمدة 15 يوماً" },
  "plan.basic.desc": { en: "200 EGP / month", ar: "200 ج.م / شهرياً" },
  "plan.premium.desc": { en: "400 EGP / month", ar: "400 ج.م / شهرياً" },
  // Super Admin tools
  "admin.tools.title": { en: "Platform Operations & Growth", ar: "عمليات ونمو المنصة" },
  "admin.tools.settings": { en: "Global Settings", ar: "الإعدادات العامة" },
  "admin.tools.basicPrice": { en: "Basic monthly price", ar: "السعر الشهري للأساسي" },
  "admin.tools.premiumPrice": { en: "Premium monthly price", ar: "السعر الشهري للمميز" },
  "admin.tools.vodafone": { en: "Vodafone Cash number", ar: "رقم فودافون كاش" },
  "admin.tools.instapay": { en: "InstaPay handle", ar: "حساب إنستاباي" },
  "admin.tools.whatsapp": { en: "WhatsApp number", ar: "رقم واتساب" },
  "admin.tools.save": { en: "Save settings", ar: "حفظ الإعدادات" },
  "admin.tools.engagement": { en: "Clinic engagement", ar: "تفاعل العيادات" },
  "admin.tools.patients": { en: "patients", ar: "مرضى" },
  "admin.tools.weekAppointments": { en: "appointments this week", ar: "مواعيد هذا الأسبوع" },
  "admin.tools.noEngagement": { en: "No engagement data yet.", ar: "لا توجد بيانات تفاعل بعد." },
  "admin.tools.broadcasts": { en: "Broadcast announcements", ar: "الإعلانات العامة" },
  "admin.tools.broadcastTitle": { en: "Announcement title", ar: "عنوان الإعلان" },
  "admin.tools.broadcastMessage": { en: "Message shown to clinic staff", ar: "الرسالة التي تظهر لموظفي العيادات" },
  "admin.tools.publish": { en: "Publish", ar: "نشر" },
  "admin.tools.archive": { en: "Archive", ar: "أرشفة" },
  "admin.tools.activate": { en: "Activate", ar: "تفعيل" },
  "admin.tools.promos": { en: "Promo codes", ar: "أكواد الخصم" },
  "admin.tools.code": { en: "Code", ar: "الكود" },
  "admin.tools.createPromo": { en: "Create code", ar: "إنشاء كود" },
  "admin.tools.disable": { en: "Disable", ar: "تعطيل" },
  "admin.tools.audit": { en: "Audit log", ar: "سجل التدقيق" },
  "admin.tools.noAudit": { en: "No audit events yet.", ar: "لا توجد أحداث تدقيق بعد." },
  "admin.tools.recommendations": { en: "Simple next steps", ar: "خطوات تالية بسيطة" },
  "admin.tools.recommendationsText": { en: "Use the engagement score to contact inactive clinics, publish important announcements, and keep payment settings updated from one place.", ar: "استخدم درجة التفاعل للتواصل مع العيادات غير النشطة، وانشر الإعلانات المهمة، وحافظ على تحديث إعدادات الدفع من مكان واحد." },
  "admin.tools.trialExtension": { en: "Trial extension", ar: "تمديد التجربة" },
  "admin.tools.days": { en: "days", ar: "أيام" },
  "admin.tools.extend": { en: "Extend", ar: "تمديد" },
  "admin.tools.trialExtended": { en: "Trial extended successfully.", ar: "تم تمديد فترة التجربة بنجاح." },
  "admin.tools.trialFailed": { en: "Could not extend the trial.", ar: "تعذر تمديد فترة التجربة." },

  // Super Admin financial reporting
  "platformFinance.title": { en: "Revenue & Financial Reports", ar: "تقارير الإيرادات والمالية" },
  "platformFinance.subtitle": { en: "Track confirmed subscription collections and payment activity across the platform.", ar: "تتبع تحصيلات الاشتراكات المؤكدة ونشاط الدفع عبر المنصة." },
  "platformFinance.selectYear": { en: "Select report year", ar: "اختر سنة التقرير" },
  "platformFinance.selectMonth": { en: "Select report month", ar: "اختر شهر التقرير" },
  "platformFinance.allMonths": { en: "All months", ar: "كل الشهور" },
  "platformFinance.export": { en: "Download CSV", ar: "تنزيل CSV" },
  "platformFinance.loadError": { en: "The financial report could not be loaded. Please try again.", ar: "تعذر تحميل التقرير المالي. يرجى المحاولة مرة أخرى." },
  "platformFinance.loading": { en: "Loading financial report...", ar: "جاري تحميل التقرير المالي..." },
  "platformFinance.totalCollected": { en: "Total collected", ar: "إجمالي التحصيل" },
  "platformFinance.transactions": { en: "Confirmed payments", ar: "المدفوعات المؤكدة" },
  "platformFinance.confirmedOnly": { en: "Approved subscription payments", ar: "مدفوعات الاشتراك المعتمدة" },
  "platformFinance.average": { en: "Average payment", ar: "متوسط الدفعة" },
  "platformFinance.perPayment": { en: "Per confirmed transaction", ar: "لكل معاملة مؤكدة" },
  "platformFinance.pending": { en: "Pending value", ar: "قيمة المدفوعات المعلقة" },
  "platformFinance.pendingRequests": { en: "pending requests", ar: "طلبات معلقة" },
  "platformFinance.monthlyTitle": { en: "Monthly collection trend", ar: "اتجاه التحصيل الشهري" },
  "platformFinance.monthlySubtitle": { en: "Confirmed subscription fees recorded in each month", ar: "رسوم الاشتراكات المؤكدة المسجلة في كل شهر" },
  "platformFinance.collected": { en: "Collected", ar: "المُحصّل" },
  "platformFinance.planTitle": { en: "Revenue by plan", ar: "الإيرادات حسب الخطة" },
  "platformFinance.clinicsTitle": { en: "Top clinics by collection", ar: "أعلى العيادات تحصيلاً" },
  "platformFinance.payments": { en: "payments", ar: "مدفوعات" },
  "platformFinance.empty": { en: "No confirmed payments for this period.", ar: "لا توجد مدفوعات مؤكدة لهذه الفترة." },
  "platformFinance.emptyChart": { en: "No confirmed payments to chart for this period.", ar: "لا توجد مدفوعات مؤكدة لعرضها في الرسم لهذه الفترة." },
  "platformFinance.transactionsTitle": { en: "Confirmed payment history", ar: "سجل المدفوعات المؤكدة" },
  "platformFinance.transactionsSubtitle": { en: "The latest 100 confirmed subscription transactions", ar: "أحدث 100 معاملة اشتراك مؤكدة" },
  "platformFinance.clinic": { en: "Clinic", ar: "العيادة" },
  "platformFinance.plan": { en: "Plan", ar: "الخطة" },
  "platformFinance.period": { en: "Period", ar: "الفترة" },
  "platformFinance.reference": { en: "Reference", ar: "المرجع" },
  "platformFinance.amount": { en: "Amount", ar: "المبلغ" },
  "platformFinance.date": { en: "Date", ar: "التاريخ" },

  // Super Admin command center
  "admin.home.subtitle": { en: "A focused command center for the health of your platform.", ar: "مركز تحكم مختصر لمتابعة حالة منصتك." },
  "admin.home.lastUpdated": { en: "Last refreshed", ar: "آخر تحديث" },
  "admin.home.last7Days": { en: "Last 7 days", ar: "آخر 7 أيام" },
  "admin.home.allConfirmed": { en: "All confirmed subscriptions", ar: "كل الاشتراكات المؤكدة" },
  "admin.home.clinicsOnPlan": { en: "Clinics currently on this plan", ar: "العيادات على هذه الخطة حالياً" },
  "admin.home.attention": { en: "Needs attention", ar: "يحتاج إلى متابعة" },
  "admin.home.viewAll": { en: "View all", ar: "عرض الكل" },
  "admin.home.viewRevenue": { en: "Open revenue report", ar: "فتح تقرير الإيرادات" },
  "admin.home.quickActions": { en: "Quick actions", ar: "إجراءات سريعة" },
  "admin.home.quickActionsSubtitle": { en: "Jump directly to the area you need to manage.", ar: "انتقل مباشرة إلى القسم الذي تريد إدارته." },
  "admin.home.clinicsShortcut": { en: "Search, filter, and review clinic activity", ar: "البحث وتصفية ومراجعة نشاط العيادات" },
  "admin.home.paymentsShortcut": { en: "Verify receipts and manage pricing", ar: "مراجعة الإيصالات وإدارة الأسعار" },
  "admin.home.growthShortcut": { en: "Publish announcements and promo codes", ar: "نشر الإعلانات وأكواد الخصم" },
  "admin.home.logsShortcut": { en: "Review administrative audit history", ar: "مراجعة سجل التدقيق الإداري" },
  "admin.home.recentSubscriptions": { en: "Latest subscription activity", ar: "أحدث نشاط للاشتراكات" },
  "admin.home.activated": { en: "Clinic activated", ar: "تم تفعيل العيادة" },
  "admin.home.activateFailed": { en: "Failed to activate clinic", ar: "فشل تفعيل العيادة" },

  // Super Admin clinics
  "platformClinics.title": { en: "Clinic Directory", ar: "دليل العيادات" },
  "platformClinics.subtitle": { en: "Manage clinic accounts, status, subscriptions, and engagement in one place.", ar: "إدارة حسابات العيادات وحالتها واشتراكاتها وتفاعلها من مكان واحد." },
  "platformClinics.export": { en: "Download CSV", ar: "تنزيل CSV" },
  "platformClinics.total": { en: "Total clinics", ar: "إجمالي العيادات" },
  "platformClinics.active": { en: "Active clinics", ar: "العيادات النشطة" },
  "platformClinics.pending": { en: "Pending clinics", ar: "العيادات المعلقة" },
  "platformClinics.trialClinics": { en: "Trial clinics", ar: "عيادات التجربة" },
  "platformClinics.search": { en: "Search by clinic, ID, request number, owner email, phone, or address...", ar: "ابحث باسم العيادة أو المعرّف أو رقم الطلب أو بريد المالك أو الهاتف أو العنوان..." },
  "platformClinics.selectAll": { en: "Select all visible clinics", ar: "تحديد كل العيادات الظاهرة" },
  "platformClinics.selectClinic": { en: "Select clinic", ar: "تحديد العيادة" },
  "platformClinics.selectedClinics": { en: "clinics selected", ar: "عيادات محددة" },
  "platformClinics.bulkActivate": { en: "Activate selected", ar: "تفعيل المحدد" },
  "platformClinics.bulkBlock": { en: "Deactivate selected", ar: "إلغاء تفعيل المحدد" },
  "platformClinics.bulkDeactivate": { en: "Deactivate selected", ar: "إلغاء تفعيل المحدد" },
  "platformClinics.clearSelection": { en: "Clear selection", ar: "مسح التحديد" },
  "platformClinics.bulkActivated": { en: "Selected clinics activated", ar: "تم تفعيل العيادات المحددة" },
  "platformClinics.bulkBlocked": { en: "Selected clinics deactivated", ar: "تم إلغاء تفعيل العيادات المحددة" },
  "platformClinics.bulkDeactivated": { en: "Selected clinics deactivated", ar: "تم إلغاء تفعيل العيادات المحددة" },
  "platformClinics.bulkFailed": { en: "Bulk clinic update failed", ar: "فشل تحديث العيادات المحددة" },
  "platformClinics.confirmBulkActivate": { en: "Activate all selected clinics?", ar: "هل تريد تفعيل كل العيادات المحددة؟" },
  "platformClinics.confirmBulkBlock": { en: "Deactivate all selected clinics? Their access will be paused.", ar: "هل تريد إلغاء تفعيل كل العيادات المحددة؟ سيتم إيقاف وصولها." },
  "platformClinics.confirmBulkDeactivate": { en: "Deactivate all selected clinics? Their access will be paused.", ar: "هل تريد إلغاء تفعيل كل العيادات المحددة؟ سيتم إيقاف وصولها." },
  "platformClinics.empty": { en: "No clinics match the current filters.", ar: "لا توجد عيادات تطابق عوامل التصفية الحالية." },
  "platformClinics.clinic": { en: "Clinic", ar: "العيادة" },
  "platformClinics.status": { en: "Status", ar: "الحالة" },
  "platformClinics.subscription": { en: "Subscription", ar: "الاشتراك" },
  "platformClinics.engagement": { en: "Engagement", ar: "التفاعل" },
  "platformClinics.activity": { en: "Activity", ar: "النشاط" },
  "platformClinics.created": { en: "Created", ar: "تاريخ الإنشاء" },
  "platformClinics.appointments": { en: "appointments", ar: "مواعيد" },
  "platformClinics.patients": { en: "patients", ar: "مرضى" },
  "platformClinics.newPatients": { en: "new in 30d", ar: "جدد خلال 30 يومًا" },
  "platformClinics.appointments30d": { en: "appointments / 30d", ar: "مواعيد / 30 يومًا" },
  "platformClinics.engagementHigh": { en: "High engagement", ar: "تفاعل مرتفع" },
  "platformClinics.engagementMedium": { en: "Medium engagement", ar: "تفاعل متوسط" },
  "platformClinics.engagementLow": { en: "Low engagement", ar: "تفاعل منخفض" },
  "platformClinics.manage": { en: "Manage", ar: "إدارة" },
  "platformClinics.extendTrial": { en: "Extend trial", ar: "تمديد التجربة" },
  "platformClinics.extendTrialTitle": { en: "Extend clinic trial", ar: "تمديد تجربة العيادة" },
  "platformClinics.extendTrialDescription": { en: "Add extra trial access without creating a payment request.", ar: "أضف مدة تجريبية إضافية دون إنشاء طلب دفع." },
  "platformClinics.trialDays": { en: "Additional days", ar: "الأيام الإضافية" },
  "platformClinics.trialDaysPlaceholder": { en: "e.g. 7", ar: "مثال: 7" },
  "platformClinics.extend": { en: "Extend", ar: "تمديد" },
  "platformClinics.trialExtended": { en: "Trial extended successfully.", ar: "تم تمديد التجربة بنجاح." },
  "platformClinics.trialFailed": { en: "Could not extend this trial.", ar: "تعذر تمديد هذه التجربة." },
  "platformClinics.expiringSoon": { en: "Expires within 3 days", ar: "ينتهي خلال 3 أيام" },
  "platformClinics.daysRemaining": { en: "days remaining", ar: "أيام متبقية" },
  "platformClinics.trialAccess": { en: "Trial access", ar: "الوصول التجريبي" },
  "platformClinics.subscriptionAccess": { en: "Subscription access", ar: "الوصول بالاشتراك" },

  // Super Admin clinic management
  "platformClinicManagement.subtitle": { en: "Manage this clinic's status, access, staff, and subscription history.", ar: "إدارة حالة العيادة ووصولها وفريقها وسجل اشتراكاتها." },
  "platformClinicManagement.backToClinics": { en: "Back to clinics", ar: "العودة إلى العيادات" },
  "platformClinicManagement.loginAsAdmin": { en: "Login as clinic admin", ar: "الدخول كمدير العيادة" },
  "platformClinicManagement.startingSession": { en: "Starting session...", ar: "جاري بدء الجلسة..." },
  "platformClinicManagement.notFound": { en: "Clinic details could not be loaded.", ar: "تعذر تحميل تفاصيل العيادة." },
  "platformClinicManagement.staff": { en: "Staff", ar: "الفريق" },
  "platformClinicManagement.patients": { en: "Patients", ar: "المرضى" },
  "platformClinicManagement.appointments": { en: "Appointments", ar: "المواعيد" },
  "platformClinicManagement.confirmedRevenue": { en: "Confirmed revenue", ar: "الإيرادات المؤكدة" },
  "platformClinicManagement.controlTitle": { en: "Clinic controls", ar: "أدوات التحكم بالعيادة" },
  "platformClinicManagement.controlSubtitle": { en: "Use these actions for support and account administration.", ar: "استخدم هذه الإجراءات للدعم وإدارة الحساب." },
  "platformClinicManagement.subscription": { en: "Subscription", ar: "الاشتراك" },
  "platformClinicManagement.trialEnds": { en: "Trial ends", ar: "تنتهي التجربة" },
  "platformClinicManagement.activate": { en: "Activate clinic", ar: "تفعيل العيادة" },
  "platformClinicManagement.deactivate": { en: "Deactivate clinic", ar: "إلغاء تفعيل العيادة" },
  "platformClinicManagement.deactivateConfirm": { en: "Deactivate this clinic? Its access will be paused, but all patient records and history will be preserved.", ar: "هل تريد إلغاء تفعيل هذه العيادة؟ سيتم إيقاف الوصول مع الحفاظ على جميع سجلات المرضى والتاريخ." },
  "platformClinicManagement.block": { en: "Deactivate clinic", ar: "إلغاء تفعيل العيادة" },
  "platformClinicManagement.extendTrial": { en: "Extend trial", ar: "تمديد التجربة" },
  "platformClinicManagement.trialDays": { en: "Days to add", ar: "عدد الأيام المضافة" },
  "platformClinicManagement.trialDaysHint": { en: "Enter any whole number from 1 to 3,650 days.", ar: "أدخل أي عدد صحيح من 1 إلى 3650 يوماً." },
  "platformClinicManagement.invalidTrialDays": { en: "Enter a valid whole number from 1 to 3,650 days.", ar: "أدخل عدداً صحيحاً صالحاً من 1 إلى 3650 يوماً." },
  "platformClinicManagement.trialExtended": { en: "Trial extended successfully.", ar: "تم تمديد التجربة بنجاح." },
  "platformClinicManagement.activated": { en: "Clinic activated.", ar: "تم تفعيل العيادة." },
  "platformClinicManagement.deactivatedSuccess": { en: "Clinic deactivated. Access is paused without deleting clinic data.", ar: "تم إلغاء تفعيل العيادة. تم إيقاف الوصول دون حذف بيانات العيادة." },
  "platformClinicManagement.blocked": { en: "Clinic deactivated.", ar: "تم إلغاء تفعيل العيادة." },
  "platformClinicManagement.trial": { en: "Trial", ar: "تجربة" },
  "platformClinicManagement.deactivated": { en: "Deactivated", ar: "غير مفعلة" },
  "platformClinicManagement.expired": { en: "Expired", ar: "منتهية" },
  "platformClinicManagement.actionFailed": { en: "The action could not be completed.", ar: "تعذر تنفيذ الإجراء." },
  "platformClinicManagement.impersonationFailed": { en: "Could not start the clinic session.", ar: "تعذر بدء جلسة العيادة." },
  "platformClinicManagement.ownerTitle": { en: "Clinic owner", ar: "مالك العيادة" },
  "platformClinicManagement.owner": { en: "Owner", ar: "المالك" },
  "platformClinicManagement.email": { en: "Email", ar: "البريد الإلكتروني" },
  "platformClinicManagement.role": { en: "Role", ar: "الدور" },
  "platformClinicManagement.joined": { en: "Joined", ar: "تاريخ الانضمام" },
  "platformClinicManagement.noOwner": { en: "No clinic owner is available.", ar: "لا يوجد مالك للعيادة." },
  "platformClinicManagement.staffTitle": { en: "Staff members", ar: "أعضاء الفريق" },
  "platformClinicManagement.name": { en: "Name", ar: "الاسم" },
  "platformClinicManagement.status": { en: "Status", ar: "الحالة" },
  "platformClinicManagement.active": { en: "Active", ar: "نشط" },
  "platformClinicManagement.subscriptionHistory": { en: "Subscription history", ar: "سجل الاشتراكات" },
  "platformClinicManagement.plan": { en: "Plan", ar: "الخطة" },
  "platformClinicManagement.amount": { en: "Amount", ar: "المبلغ" },
  "platformClinicManagement.date": { en: "Date", ar: "التاريخ" },

  // Super Admin payments
  "platformPayments.title": { en: "Payments & Plans", ar: "المدفوعات والخطط" },
  "platformPayments.subtitle": { en: "Review manual payments, activate subscriptions, and track confirmed payment history.", ar: "مراجعة المدفوعات اليدوية وتفعيل الاشتراكات ومتابعة سجل المدفوعات المؤكدة." },
  "platformPayments.pending": { en: "Pending confirmations", ar: "تأكيدات معلقة" },
  "platformPayments.confirmed": { en: "Confirmed payments", ar: "المدفوعات المؤكدة" },
  "platformPayments.workflow": { en: "Payment workflow", ar: "سير عمل الدفع" },
  "platformPayments.manualVerification": { en: "Manual verification", ar: "مراجعة يدوية" },
  "platformPayments.pendingTitle": { en: "Pending payment confirmations", ar: "تأكيدات الدفع المعلقة" },
  "platformPayments.pendingSubtitle": { en: "Review receipt screenshots and choose the exact access duration before activation.", ar: "راجع صور الإيصالات واختر مدة الوصول قبل التفعيل." },
  "platformPayments.emptyPending": { en: "No pending payment confirmations.", ar: "لا توجد تأكيدات دفع معلقة." },
  "platformPayments.pendingBadge": { en: "Pending verification", ar: "في انتظار المراجعة" },
  "platformPayments.month": { en: "month", ar: "شهر" },
  "platformPayments.months": { en: "months", ar: "أشهر" },
  "platformPayments.year": { en: "year", ar: "سنة" },
  "platformPayments.years": { en: "years", ar: "سنوات" },
  "platformPayments.amount": { en: "Amount", ar: "المبلغ" },
  "platformPayments.submitted": { en: "Submitted", ar: "تاريخ الإرسال" },
  "platformPayments.reference": { en: "Reference", ar: "المرجع" },
  "platformPayments.receiptAlt": { en: "Payment receipt screenshot", ar: "صورة إيصال الدفع" },
  "platformPayments.viewReceipt": { en: "View receipt", ar: "عرض الإيصال" },
  "platformPayments.proofAvailable": { en: "Payment proof is available for review.", ar: "إثبات الدفع متاح للمراجعة." },
  "platformPayments.chatWhatsApp": { en: "Chat on WhatsApp", ar: "محادثة عبر واتساب" },
  "platformPayments.whatsappUnavailable": { en: "No WhatsApp number available", ar: "لا يوجد رقم واتساب متاح" },
  "platformPayments.whatsappMessage": { en: "Hello {name}, this is ClinicSquad support regarding your subscription payment for {clinic}. We are reviewing your receipt and may need a few more details.", ar: "مرحباً {name}، معك دعم ClinicSquad بخصوص دفعة اشتراك عيادتك {clinic}. نراجع الإيصال وقد نحتاج إلى بعض التفاصيل الإضافية." },
  "platformPayments.grantDuration": { en: "Grant access duration", ar: "مدة منح الوصول" },
  "platformPayments.approve": { en: "Approve & activate", ar: "موافقة وتفعيل" },
  "platformPayments.confirmedToast": { en: "Payment confirmed and subscription activated.", ar: "تم تأكيد الدفع وتفعيل الاشتراك." },
  "platformPayments.confirmFailed": { en: "Could not confirm this payment.", ar: "تعذر تأكيد هذا الدفع." },
  "platformPayments.historyTitle": { en: "Confirmed payment history", ar: "سجل المدفوعات المؤكدة" },

  // Super Admin platform settings
  "platformSettings.title": { en: "Platform Settings", ar: "إعدادات المنصة" },
  "platformSettings.subtitle": { en: "Manage the prices and payment contacts shown to clinic administrators during checkout.", ar: "إدارة الأسعار وبيانات الدفع التي تظهر لمديري العيادات أثناء الدفع." },
  "platformSettings.info": { en: "Changes apply to the checkout instructions and pricing displayed across the platform. Review values carefully before saving.", ar: "تُطبّق التغييرات على تعليمات الدفع والأسعار المعروضة في جميع أنحاء المنصة. راجع البيانات بعناية قبل الحفظ." },
  "platformSettings.loading": { en: "Loading platform settings...", ar: "جارٍ تحميل إعدادات المنصة..." },
  "platformSettings.lastUpdated": { en: "Last updated", ar: "آخر تحديث" },
  "platformSettings.pricingTitle": { en: "Subscription pricing", ar: "أسعار الاشتراك" },
  "platformSettings.pricingSubtitle": { en: "Set the monthly prices used for Basic and Premium plans.", ar: "حدد الأسعار الشهرية المستخدمة للخطتين الأساسية والمميزة." },
  "platformSettings.paymentTitle": { en: "Payment contacts", ar: "بيانات الدفع" },
  "platformSettings.paymentSubtitle": { en: "These details are shown to clinic administrators when they submit a manual payment.", ar: "تظهر هذه البيانات لمديري العيادات عند إرسال دفعة يدوية." },
  "platformSettings.save": { en: "Save platform settings", ar: "حفظ إعدادات المنصة" },
  "platformSettings.saved": { en: "Platform settings saved.", ar: "تم حفظ إعدادات المنصة." },
  "platformSettings.saveFailed": { en: "Could not save platform settings.", ar: "تعذر حفظ إعدادات المنصة." },
  "platformPayments.historySubtitle": { en: "Recent manual subscription payments", ar: "أحدث مدفوعات الاشتراك اليدوية" },
  "platformPayments.emptyHistory": { en: "No confirmed payments yet.", ar: "لا توجد مدفوعات مؤكدة بعد." },
  "platformPayments.clinic": { en: "Clinic", ar: "العيادة" },
  "platformPayments.plan": { en: "Plan", ar: "الخطة" },
  "platformPayments.period": { en: "Period", ar: "الفترة" },
  "platformPayments.confirmedDate": { en: "Date", ar: "التاريخ" },

  // Super Admin growth tools
  "platformGrowth.title": { en: "Growth Tools", ar: "أدوات النمو" },
  "platformGrowth.subtitle": { en: "Communicate with clinics and create simple incentives for new subscriptions.", ar: "تواصل مع العيادات وأنشئ حوافز بسيطة للاشتراكات الجديدة." },
  "platformGrowth.broadcastSubtitle": { en: "Announcements appear as banners for clinic staff.", ar: "تظهر الإعلانات كشرائط لموظفي العيادات." },
  "platformGrowth.promoSubtitle": { en: "Offer percentage discounts during campaigns or special periods.", ar: "قدم خصومات نسبية أثناء الحملات أو الفترات الخاصة." },
  "platformGrowth.broadcastCreated": { en: "Broadcast published.", ar: "تم نشر الإعلان." },
  "platformGrowth.promoCreated": { en: "Promo code created.", ar: "تم إنشاء كود الخصم." },
  "platformGrowth.actionFailed": { en: "Could not complete the action.", ar: "تعذر تنفيذ الإجراء." },
  "platformGrowth.noBroadcasts": { en: "No broadcasts created yet.", ar: "لم يتم إنشاء إعلانات بعد." },
  "platformGrowth.noPromos": { en: "No promo codes created yet.", ar: "لم يتم إنشاء أكواد خصم بعد." },
  "platformGrowth.expires": { en: "Expires", ar: "ينتهي" },

  // Super Admin logs
  "platformLogs.title": { en: "System Logs", ar: "سجلات النظام" },
  "platformLogs.subtitle": { en: "Review the administrative activity history for accountability and security.", ar: "راجع سجل النشاط الإداري للمساءلة والأمان." },
  "platformLogs.total": { en: "Total events", ar: "إجمالي الأحداث" },
  "platformLogs.today": { en: "Events today", ar: "أحداث اليوم" },
  "platformLogs.actionTypes": { en: "Action types", ar: "أنواع الإجراءات" },
  "platformLogs.historyTitle": { en: "Audit history", ar: "سجل التدقيق" },
  "platformLogs.historySubtitle": { en: "Administrative actions recorded by the platform", ar: "الإجراءات الإدارية المسجلة بواسطة المنصة" },
  "platformLogs.search": { en: "Search logs...", ar: "البحث في السجلات..." },
  "platformLogs.loading": { en: "Loading audit history...", ar: "جاري تحميل سجل التدقيق..." },
  "platformLogs.empty": { en: "No audit events match your search.", ar: "لا توجد أحداث تدقيق تطابق بحثك." },
  "platformLogs.securityTitle": { en: "Keep your audit trail useful", ar: "حافظ على فائدة سجل التدقيق" },
  "platformLogs.securityText": { en: "Use the log to review pricing changes, payment confirmations, broadcasts, and promotional activity over time.", ar: "استخدم السجل لمراجعة تغييرات الأسعار وتأكيدات الدفع والإعلانات وأكواد الخصم بمرور الوقت." },
  "platformLogs.refresh": { en: "Refresh", ar: "تحديث" },

  // Missing page-level labels
  "invite.toast.welcome": { en: "Welcome to ClinicSquad", ar: "مرحباً بك في كلينيك سكواد" },
  "invite.toast.failed": { en: "Could not accept invitation", ar: "تعذر قبول الدعوة" },
  "invite.toast.failedDesc": { en: "Please check the invitation and try again.", ar: "يرجى التحقق من الدعوة والمحاولة مرة أخرى." },
  "invite.invalid.title": { en: "Invitation unavailable", ar: "الدعوة غير متاحة" },
  "invite.invalid.body": { en: "This invitation is invalid or has expired.", ar: "هذه الدعوة غير صالحة أو انتهت صلاحيتها." },
  "invite.title": { en: "Accept your invitation", ar: "قبول دعوتك" },
  "invite.subtitle.prefix": { en: "You were invited to join", ar: "تمت دعوتك للانضمام إلى" },
  "invite.subtitle.as": { en: "as", ar: "بصفة" },
  "invite.email": { en: "Email", ar: "البريد الإلكتروني" },
  "invite.fullName": { en: "Full name", ar: "الاسم الكامل" },
  "invite.password": { en: "Password", ar: "كلمة المرور" },
  "invite.accept": { en: "Accept invitation", ar: "قبول الدعوة" },

  "appt.searchPh": { en: "Search appointments...", ar: "ابحث في المواعيد..." },
  "appt.typePh": { en: "Select appointment type", ar: "اختر نوع الموعد" },
  "appt.toast.created": { en: "Appointment created", ar: "تم إنشاء الموعد" },
  "appt.toast.failed": { en: "Could not save appointment", ar: "تعذر حفظ الموعد" },
  "appt.confirmDelete": { en: "Delete this appointment?", ar: "هل تريد حذف هذا الموعد؟" },
  "appt.toast.deleted": { en: "Appointment deleted", ar: "تم حذف الموعد" },
  "appt.noAppts": { en: "No appointments scheduled for this day", ar: "لا توجد مواعيد مجدولة لهذا اليوم" },
  "appt.whatsapp": { en: "Contact on WhatsApp", ar: "التواصل عبر واتساب" },
  "appt.notes": { en: "Notes", ar: "ملاحظات" },
  "appt.save": { en: "Save appointment", ar: "حفظ الموعد" },

  "finances.toast.failed": { en: "Could not save transaction", ar: "تعذر حفظ المعاملة" },
  "finances.toast.added": { en: "Transaction added", ar: "تمت إضافة المعاملة" },
  "finances.save": { en: "Save transaction", ar: "حفظ المعاملة" },

  "dash.today.checkedIn": { en: "Checked in today", ar: "تم تسجيل دخولهم اليوم" },
  "dash.today.checkin": { en: "Check in", ar: "تسجيل الدخول" },
  "dash.tomorrow.scheduled": { en: "Scheduled for tomorrow", ar: "مجدول للغد" },
  "dash.tomorrow.send": { en: "Send reminder", ar: "إرسال تذكير" },
  "dash.tomorrow.noPhone": { en: "No phone number", ar: "لا يوجد رقم هاتف" },

  "insights.chart.revenueTitle": { en: "Revenue trend", ar: "اتجاه الإيرادات" },
  "insights.chart.revenueSub": { en: "Monthly revenue performance", ar: "أداء الإيرادات الشهرية" },

  "patients.toast.added": { en: "Patient added", ar: "تمت إضافة المريض" },
  "patients.confirmDelete": { en: "Are you sure you want to delete this patient?", ar: "هل أنت متأكد من رغبتك في حذف هذا المريض؟" },
  "patients.toast.deleted": { en: "Patient deleted", ar: "تم حذف المريض" },
  "patients.toast.deleteFailed": { en: "Could not delete patient", ar: "تعذر حذف المريض" },
  "patients.tryDifferent": { en: "Try a different search", ar: "جرّب بحثاً مختلفاً" },
  "patients.blood": { en: "Blood type", ar: "فصيلة الدم" },
  "patients.alreadyOnQueue": { en: "Already in queue", ar: "موجود بالفعل في قائمة الانتظار" },
  "patients.sendToQueue": { en: "Send to queue", ar: "إرسال إلى قائمة الانتظار" },
  "patients.onQueue": { en: "On queue", ar: "في قائمة الانتظار" },
  "patients.fullNamePh": { en: "Enter patient's full name", ar: "أدخل الاسم الكامل للمريض" },

  "pending.status": { en: "Pending activation", ar: "في انتظار التفعيل" },
  "pending.body": { en: "Your clinic account is awaiting Super Admin activation.", ar: "حساب عيادتك في انتظار تفعيل المدير العام." },
  "pending.clinic": { en: "Clinic", ar: "العيادة" },
  "pending.account": { en: "Account", ar: "الحساب" },
  "pending.reqNum": { en: "Request number", ar: "رقم الطلب" },
  "pending.reqNumNote": { en: "Keep this number for support", ar: "احتفظ بهذا الرقم للدعم" },
  "pending.step1": { en: "Submit your clinic request", ar: "أرسل طلب عيادتك" },
  "pending.step2": { en: "Wait for verification", ar: "انتظر التحقق" },
  "pending.step3": { en: "Start using ClinicSquad", ar: "ابدأ باستخدام كلينيك سكواد" },
  "pending.footer": { en: "We will notify you when your account is activated.", ar: "سنُخطرك عند تفعيل حسابك." },

  "presc.print": { en: "Print prescription", ar: "طباعة الوصفة الطبية" },
  "presc.whatsapp": { en: "Send via WhatsApp", ar: "إرسال عبر واتساب" },
  "presc.previewNote": { en: "Preview", ar: "معاينة" },
  "presc.rxDraft": { en: "Prescription draft", ar: "مسودة وصفة طبية" },
  "presc.doctor": { en: "Dr.", ar: "د." },
  "presc.medPractitioner": { en: "Medical practitioner", ar: "ممارس طبي" },
  "presc.patientName": { en: "Patient", ar: "المريض" },
  "presc.phone": { en: "Phone", ar: "الهاتف" },
  "presc.rxId": { en: "Prescription ID", ar: "معرّف الوصفة" },
  "presc.draft": { en: "Draft", ar: "مسودة" },
  "presc.notesForPatient": { en: "Notes for patient", ar: "ملاحظات للمريض" },
  "presc.address": { en: "Address", ar: "العنوان" },
};

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("clinic_lang");
    return (saved as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("clinic_lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: string) => {
    return translations[key]?.[lang] || key;
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LangContext);
  if (!context) throw new Error("useLang must be used within LangProvider");
  return context;
}
