import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "ar";

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<string, Record<Lang, string>> = {
  // Nav
  "nav.features": { en: "Features", ar: "المميزات" },
  "nav.howItWorks": { en: "How It Works", ar: "كيف تعمل" },
  "nav.pricing": { en: "Pricing", ar: "الأسعار" },
  "nav.testimonials": { en: "Testimonials", ar: "آراء العملاء" },
  "nav.signIn": { en: "Sign In", ar: "تسجيل الدخول" },
  "nav.startTrial": { en: "Start Free Trial", ar: "ابدأ التجربة المجانية" },
  // Hero
  "hero.badge": { en: "15-Day Free Trial — No Credit Card Required", ar: "تجربة مجانية 15 يوماً — بدون بطاقة ائتمانية" },
  "hero.title1": { en: "The Clinic OS for", ar: "نظام إدارة العيادة لـ" },
  "hero.title2": { en: "Modern Medicine", ar: "الطب الحديث" },
  "hero.subtitle": { en: "ClinicSquad gives Egyptian doctors and clinic owners a complete management platform — patients, appointments, finances, and staff — in one powerful workspace.", ar: "كلينيك سكواد يمنح الأطباء المصريين وأصحاب العيادات منصة إدارة متكاملة — المرضى والمواعيد والمالية والموظفين — في مكان عمل واحد قوي." },
  "hero.cta1": { en: "Start Your Free Trial", ar: "ابدأ تجربتك المجانية" },
  "hero.cta2": { en: "Sign In to Dashboard", ar: "تسجيل الدخول للوحة التحكم" },
  "hero.stat.clinics": { en: "Clinics", ar: "عيادة" },
  "hero.stat.patients": { en: "Patients", ar: "مريض" },
  "hero.stat.trial": { en: "Free Trial", ar: "تجربة مجانية" },
  // Features
  "feat.title": { en: "Everything Your Clinic Needs", ar: "كل ما تحتاجه عيادتك" },
  "feat.subtitle": { en: "A complete clinical management system built specifically for Egyptian healthcare practices.", ar: "نظام إدارة عيادات متكامل مصمم خصيصاً للرعاية الصحية المصرية." },
  "feat.patients.title": { en: "Patient Management", ar: "إدارة المرضى" },
  "feat.patients.desc": { en: "Comprehensive patient records with medical history, allergies, and contact details.", ar: "سجلات مرضى شاملة مع التاريخ الطبي والحساسيات وبيانات التواصل." },
  "feat.scheduling.title": { en: "Smart Scheduling", ar: "جدولة ذكية" },
  "feat.scheduling.desc": { en: "Effortless appointment booking with status tracking and daily views.", ar: "حجز مواعيد بسهولة مع تتبع الحالة وعرض يومي." },
  "feat.finance.title": { en: "Financial Dashboard", ar: "لوحة المالية" },
  "feat.finance.desc": { en: "Track income, expenses, and generate monthly financial reports.", ar: "تتبع الإيرادات والمصروفات وإنشاء تقارير مالية شهرية." },
  "feat.realtime.title": { en: "Real-time Updates", ar: "تحديثات فورية" },
  "feat.realtime.desc": { en: "Instant updates across all devices — always see the latest clinic data.", ar: "تحديثات فورية على جميع الأجهزة — شاهد دائماً أحدث بيانات العيادة." },
  "feat.secure.title": { en: "Secure & Compliant", ar: "آمن ومتوافق" },
  "feat.secure.desc": { en: "Role-based access control for admins, secretaries and clinic staff.", ar: "تحكم في الوصول بحسب الدور للمدراء والسكرتيرة وموظفي العيادة." },
  "feat.bilingual.title": { en: "Arabic & English", ar: "عربي وإنجليزي" },
  "feat.bilingual.desc": { en: "Full support for both Arabic (RTL) and English language interfaces.", ar: "دعم كامل للغة العربية (RTL) وواجهات اللغة الإنجليزية." },
  // Pricing
  "pricing.title": { en: "Simple, Transparent Pricing", ar: "أسعار بسيطة وشفافة" },
  "pricing.subtitle": { en: "Start with a 15-day free trial. No credit card required.", ar: "ابدأ بتجربة مجانية 15 يوماً. لا حاجة لبطاقة ائتمانية." },
  "pricing.popular": { en: "Most Popular", ar: "الأكثر شيوعاً" },
  "pricing.basic.name": { en: "Basic Plan", ar: "الخطة الأساسية" },
  "pricing.basic.desc": { en: "Perfect for small clinics", ar: "مثالية للعيادات الصغيرة" },
  "pricing.premium.name": { en: "Premium Plan", ar: "الخطة المميزة" },
  "pricing.premium.desc": { en: "Full-featured for growing clinics", ar: "متكاملة للعيادات النامية" },
  "pricing.cta": { en: "Start Free Trial", ar: "ابدأ التجربة المجانية" },
  // How it works
  "how.title": { en: "How to Get Started with ClinicSquad?", ar: "كيف تبدأ مع كلينيك سكواد؟" },
  "how.subtitle": { en: "Four simple steps from sign-up to a fully running, data-driven clinic.", ar: "أربع خطوات بسيطة من التسجيل إلى عيادة متكاملة تعمل بالبيانات." },
  "how.step1.title": { en: "Create Your Account", ar: "أنشئ حسابك" },
  "how.step1.desc": { en: "Register in seconds — no credit card required. Set up your clinic profile with your name, specialty, and consultation fees.", ar: "سجّل في ثوانٍ — بدون بطاقة ائتمانية. أنشئ ملف عيادتك مع اسمك وتخصصك ورسوم الكشف." },
  "how.step2.title": { en: "Customize Your Settings", ar: "خصّص إعداداتك" },
  "how.step2.desc": { en: "Configure consultation fees, add doctors and secretary accounts, and personalize the system to match your daily workflow.", ar: "حدّد رسوم الكشف، أضف حسابات الأطباء والسكرتيرة، وخصّص النظام ليناسب سير عملك اليومي." },
  "how.step3.title": { en: "Add Patients & Book Appointments", ar: "أضف المرضى واحجز المواعيد" },
  "how.step3.desc": { en: "Start adding patient records and booking appointments. The system handles the waitlist, visit history, and billing automatically.", ar: "ابدأ بإضافة سجلات المرضى وحجز المواعيد. النظام يتولى قائمة الانتظار وسجل الزيارات والفواتير تلقائياً." },
  "how.step4.title": { en: "Track & Grow", ar: "تابع وانمُ" },
  "how.step4.desc": { en: "Monitor clinic performance, revenue trends, and patient statistics from a beautiful analytics dashboard.", ar: "تابع أداء عيادتك واتجاهات الإيرادات وإحصائيات المرضى من لوحة تحليلات أنيقة." },
  "test.title": { en: "Trusted by Egyptian Doctors", ar: "موثوق به من الأطباء المصريين" },
  // CTA Section
  "cta.title": { en: "Ready to Transform Your Clinic?", ar: "مستعد لتحويل عيادتك؟" },
  "cta.subtitle": { en: "Join hundreds of Egyptian clinics already using ClinicSquad to streamline their operations.", ar: "انضم لمئات العيادات المصرية التي تستخدم كلينيك سكواد لتبسيط عملياتها." },
  "cta.btn1": { en: "Start Free Trial — 15 Days", ar: "ابدأ التجربة المجانية — 15 يوماً" },
  "cta.btn2": { en: "Contact via WhatsApp", ar: "تواصل عبر واتساب" },
  
  // Auth Pages
  "auth.login.title": { en: "Welcome back", ar: "مرحباً بعودتك" },
  "auth.login.subtitle": { en: "Sign in to your clinic account", ar: "سجّل الدخول إلى حساب عيادتك" },
  "auth.login.email": { en: "Email", ar: "البريد الإلكتروني" },
  "auth.login.password": { en: "Password", ar: "كلمة المرور" },
  "auth.login.forgot": { en: "Forgot password?", ar: "نسيت كلمة المرور؟" },
  "auth.login.submit": { en: "Sign In", ar: "تسجيل الدخول" },
  "auth.login.noAccount": { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
  "auth.login.register": { en: "Register your clinic", ar: "سجّل عيادتك" },
  "auth.login.hero.title": { en: "The command center for your clinic", ar: "مركز القيادة لعيادتك" },
  "auth.login.hero.subtitle": { en: "Manage patients, appointments, and finances — all in one place, built for Egyptian clinics.", ar: "أدِر المرضى والمواعيد والمالية — كل ذلك في مكان واحد، مصمم للعيادات المصرية." },
  "auth.login.hero.feat1": { en: "Patient management", ar: "إدارة المرضى" },
  "auth.login.hero.feat2": { en: "Appointment scheduling", ar: "جدولة المواعيد" },
  "auth.login.hero.feat3": { en: "Financial tracking", ar: "تتبع المالية" },

  "auth.register.title": { en: "Start your free trial", ar: "ابدأ تجربتك المجانية" },
  "auth.register.subtitle": { en: "Join 500+ clinics using ClinicSquad to grow.", ar: "انضم لأكثر من 500 عيادة تستخدم كلينيك سكواد للنمو." },
  "auth.register.name": { en: "Clinic Name", ar: "اسم العيادة" },
  "auth.register.owner": { en: "Doctor Name", ar: "اسم الطبيب" },
  "auth.register.email": { en: "Work Email", ar: "بريد العمل" },
  "auth.register.password": { en: "Password", ar: "كلمة المرور" },
  "auth.register.submit": { en: "Create Clinic Account", ar: "إنشاء حساب العيادة" },
  "auth.register.haveAccount": { en: "Already have an account?", ar: "لديك حساب بالفعل؟" },
  "auth.register.login": { en: "Sign in instead", ar: "سجّل الدخول بدلاً من ذلك" },
  "auth.register.hero.title": { en: "Request your free 15-day trial", ar: "اطلب تجربتك المجانية لمدة 15 يوماً" },
  "auth.register.hero.subtitle": { en: "Tell us about your clinic and our team will activate your trial within minutes.", ar: "أخبرنا عن عيادتك وسيقوم فريقنا بتفعيل تجربتك في غضون دقائق." },
  "auth.register.hero.feat1": { en: "Full access during trial", ar: "وصول كامل خلال فترة التجربة" },
  "auth.register.hero.feat2": { en: "Both Basic and Premium features", ar: "كل المميزات الأساسية والمتقدمة" },
  "auth.register.hero.feat3": { en: "Cancel anytime — no credit card", ar: "إلغاء في أي وقت — بدون بطاقة ائتمانية" },
  "auth.register.hero.trusted": { en: "Trusted by 500+ Egyptian clinics", ar: "موثوق به من أكثر من 500 عيادة مصرية" },
  "auth.register.specialty": { en: "Medical Specialty", ar: "التخصص الطبي" },
  "auth.register.whatsapp": { en: "WhatsApp Number", ar: "رقم الواتساب" },
  "auth.register.terms": { en: "By requesting a trial, you agree to our Terms of Service and Privacy Policy.", ar: "بطلبك للتجربة، فإنك توافق على شروط الخدمة وسياسة الخصوصية الخاصة بنا." },

  // Dashboard sidebar
  "sidebar.clinic": { en: "Clinic", ar: "العيادة" },
  "sidebar.dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "sidebar.patients": { en: "Patients", ar: "المرضى" },
  "sidebar.appointments": { en: "Appointments", ar: "المواعيد" },
  "sidebar.waitingList": { en: "Waiting List", ar: "قائمة الانتظار" },
  "sidebar.checkout": { en: "Checkout", ar: "الحساب" },
  "sidebar.insights": { en: "Insights", ar: "التحليلات" },
  "sidebar.finances": { en: "Finances", ar: "المالية" },
  "sidebar.settings": { en: "Settings", ar: "الإعدادات" },
  "sidebar.admin": { en: "Admin Panel", ar: "لوحة الإدارة" },
  "sidebar.team": { en: "Team", ar: "الفريق" },
  "sidebar.prescriptions": { en: "ePrescription", ar: "الوصفة الإلكترونية" },
  "sidebar.signOut": { en: "Sign Out", ar: "تسجيل الخروج" },

  // Common
  "common.trialLeft": { en: " days left in trial", ar: " أيام متبقية في التجربة" },
  "common.upgradePlan": { en: "Upgrade Plan", ar: "ترقية الخطة" },
  "common.upgrade": { en: "Upgrade Now", ar: "ترقية الآن" },
  "common.subExpired": { en: "Subscription Expired", ar: "انتهى الاشتراك" },
  "common.trialExpires": { en: "Trial expires in", ar: "تنتهي التجربة خلال" },
  "common.day": { en: "day", ar: "يوم" },
  "common.days": { en: "days", ar: "أيام" },
  "common.upgradeNow": { en: "Upgrade Now", ar: "ترقية الآن" },

  // Statuses
  "status.inProgress": { en: "In progress", ar: "قيد الكشف" },
  "status.waiting": { en: "Waiting", ar: "في الانتظار" },
  "status.completed": { en: "Completed", ar: "مكتمل" },
  "status.registered": { en: "Registered", ar: "مسجل" },
  "status.scheduled": { en: "Scheduled", ar: "مجدول" },
  "status.cancelled": { en: "Cancelled", ar: "ملغي" },
  "status.noShow": { en: "No Show", ar: "لم يحضر" },
  "status.checkedIn": { en: "Checked-in", ar: "تم الدخول" },

  // Prescriptions
  "presc.title": { en: "ePrescription", ar: "الوصفة الإلكترونية" },
  "presc.subtitle": { en: "Write, print, and send prescriptions to your patients.", ar: "اكتب واطبع وأرسل الوصفات الطبية لمرضاك." },
  "presc.new": { en: "New Prescription", ar: "وصفة جديدة" },
  "presc.cancel": { en: "Cancel", ar: "إلغاء" },
  "presc.selectPatient": { en: "Select a patient", ar: "اختر مريضاً" },
  "presc.addMedication": { en: "Add at least one medication", ar: "أضف دواءً واحداً على الأقل" },
  "presc.created": { en: "Prescription created", ar: "تم إنشاء الوصفة" },
  "presc.failed": { en: "Failed to create prescription", ar: "فشل إنشاء الوصفة" },
  "presc.confirmDelete": { en: "Delete this prescription?", ar: "حذف هذه الوصفة؟" },
  "presc.deleted": { en: "Deleted", ar: "تم الحذف" },
  "presc.failedDelete": { en: "Failed to delete", ar: "فشل الحذف" },
  "presc.patient": { en: "Patient", ar: "المريض" },
  "presc.selectPatientPh": { en: "Select patient", ar: "اختر المريض" },
  "presc.date": { en: "Date", ar: "التاريخ" },
  "presc.diagnosis": { en: "Diagnosis", ar: "التشخيص" },
  "presc.diagnosisPh": { en: "e.g. Acute pharyngitis", ar: "مثال: التهاب الحلق الحاد" },
  "presc.medications": { en: "Medications", ar: "الأدوية" },
  "presc.addMedBtn": { en: "Add medication", ar: "أضف دواء" },
  "presc.drugName": { en: "Drug name", ar: "اسم الدواء" },
  "presc.drugNamePh": { en: "e.g. Amoxicillin 500mg", ar: "مثال: أموكسيسيلين 500 مجم" },
  "presc.dosage": { en: "Dosage", ar: "الجرعة" },
  "presc.dosagePh": { en: "1 capsule", ar: "كبسولة واحدة" },
  "presc.frequency": { en: "Frequency", ar: "التكرار" },
  "presc.frequencyPh": { en: "3× daily", ar: "3 مرات يومياً" },
  "presc.duration": { en: "Duration", ar: "المدة" },
  "presc.durationPh": { en: "7 days", ar: "7 أيام" },
  "presc.clinicalNotes": { en: "Clinical Notes", ar: "ملاحظات سريرية" },
  "presc.clinicalNotesPh": { en: "e.g. Take after meals, complete the course", ar: "مثال: تؤخذ بعد الوجبات، أكمل الجرعة" },
  "presc.save": { en: "Save Prescription", ar: "حفظ الوصفة" },
  "presc.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "presc.empty": { en: "No prescriptions found", ar: "لم يتم العثور على وصفات" },
  "presc.searchPh": { en: "Search by patient, diagnosis, or drug name", ar: "البحث بالمريض أو التشخيص أو اسم الدواء" },
  "presc.delete": { en: "Delete", ar: "حذف" },
  "presc.view": { en: "View", ar: "عرض" },
  "presc.preview": { en: "Live preview", ar: "معاينة مباشرة" },

  // Dashboard
  "dash.title": { en: "Dashboard", ar: "لوحة التحكم" },
  "dash.stats.totalPatients": { en: "Total Patients", ar: "إجمالي المرضى" },
  "dash.stats.newThisMonth": { en: "new this month", ar: "جديد هذا الشهر" },
  "dash.stats.todayAppts": { en: "Today's Appointments", ar: "مواعيد اليوم" },
  "dash.stats.upcoming": { en: "upcoming", ar: "قادم" },
  "dash.stats.completed": { en: "Completed Sessions", ar: "الجلسات المكتملة" },
  "dash.stats.total": { en: "total sessions", ar: "إجمالي الجلسات" },
  "dash.today.title": { en: "Today's Schedule", ar: "جدول اليوم" },
  "dash.today.viewAll": { en: "View all appointments", ar: "عرض كل المواعيد" },
  "dash.today.empty": { en: "No appointments for today", ar: "لا توجد مواعيد اليوم" },
  "dash.today.schedule": { en: "Schedule appointment", ar: "جدولة موعد" },
  "dash.tomorrow.title": { en: "Tomorrow", ar: "غداً" },
  "dash.tomorrow.subtitle": { en: "Upcoming schedule", ar: "الجدول القادم" },
  "dash.tomorrow.empty": { en: "No appointments for tomorrow", ar: "لا توجد مواعيد لغد" },
  "dash.stats.waiting": { en: "In Waiting List", ar: "في قائمة الانتظار" },
  "dash.stats.revenue": { en: "Total Revenue", ar: "إجمالي الإيرادات" },
  "dash.stats.activeTrial": { en: "Active Trial", ar: "تجربة نشطة" },
  "dash.stats.daysLeft": { en: "days left", ar: "أيام متبقية" },
  "dash.recentAppts": { en: "Recent Appointments", ar: "المواعيد الأخيرة" },
  "dash.viewAll": { en: "View All", ar: "عرض الكل" },
  "dash.noAppts": { en: "No appointments today", ar: "لا توجد مواعيد اليوم" },
  "dash.revenueOverview": { en: "Revenue Overview", ar: "نظرة عامة على الإيرادات" },

  // Patients
  "patients.title": { en: "Patients", ar: "المرضى" },
  "patients.subtitle": { en: "Manage your patient records and medical history.", ar: "أدِر سجلات مرضاك وتاريخهم الطبي." },
  "patients.new": { en: "New Patient", ar: "مريض جديد" },
  "patients.add": { en: "Add Patient", ar: "أضف مريضاً" },
  "patients.onFile": { en: "patients on file", ar: "مريض مسجل" },
  "patients.searchPh": { en: "Search patients (PT-0001, name, phone)...", ar: "البحث عن المرضى (PT-0001، الاسم، الهاتف)..." },
  "patients.id": { en: "ID", ar: "المعرف" },
  "patients.name": { en: "Name", ar: "الاسم" },
  "patients.age": { en: "Age", ar: "السن" },
  "patients.phone": { en: "Phone", ar: "الهاتف" },
  "patients.visitType": { en: "Visit Type", ar: "نوع الزيارة" },
  "patients.status": { en: "Status", ar: "الحالة" },
  "patients.dateAdded": { en: "Date Added", ar: "تاريخ الإضافة" },
  "patients.actions": { en: "Actions", ar: "الإجراءات" },
  "patients.notFound": { en: "No patients found", ar: "لم يتم العثور على مرضى" },
  "patients.empty": { en: "No patients yet", ar: "لا يوجد مرضى بعد" },
  "patients.addFirst": { en: "Add your first patient to get started", ar: "أضف أول مريض للبدء" },
  "patients.toast.created": { en: "Patient created successfully", ar: "تم إنشاء المريض بنجاح" },
  "patients.toast.failed": { en: "Failed to create patient", ar: "فشل إنشاء المريض" },
  "patients.toast.sentToQueue": { en: "sent to waiting list", ar: "تم إرساله لقائمة الانتظار" },
  "patients.toast.checkInFailed": { en: "Failed to check in", ar: "فشل الدخول" },
  "patients.checkIn": { en: "Check-in", ar: "دخول" },

  // Waiting List
  "waiting.title": { en: "Waiting List", ar: "قائمة الانتظار" },
  "waiting.subtitle": { en: "Manage patients currently waiting for their consultation.", ar: "أدِر المرضى الذين ينتظرون كشفهم حالياً." },
  "waiting.empty": { en: "Waiting list is empty", ar: "قائمة الانتظار فارغة" },
  "waiting.callNext": { en: "Call Next Patient", ar: "نداء المريض التالي" },
  "waiting.patient": { en: "Patient", ar: "المريض" },
  "waiting.time": { en: "Wait Time", ar: "وقت الانتظار" },
  "waiting.type": { en: "Type", ar: "النوع" },
  "waiting.actions": { en: "Actions", ar: "الإجراءات" },
  "waiting.start": { en: "Start Session", ar: "بدء الجلسة" },
  "waiting.remove": { en: "Remove", ar: "إزالة" },

  // Checkout
  "checkout.title": { en: "Checkout & Billing", ar: "الحساب والفواتير" },
  "checkout.subtitle": { en: "Process payments and complete patient sessions.", ar: "معالجة المدفوعات وإتمام جلسات المرضى." },
  "checkout.empty": { en: "No patients ready for checkout", ar: "لا يوجد مرضى جاهزون للحساب" },
  "checkout.patient": { en: "Patient", ar: "المريض" },
  "checkout.amount": { en: "Amount", ar: "المبلغ" },
  "checkout.status": { en: "Status", ar: "الحالة" },
  "checkout.actions": { en: "Actions", ar: "الإجراءات" },
  "checkout.process": { en: "Process Payment", ar: "دفع الحساب" },
  "checkout.complete": { en: "Complete Session", ar: "إتمام الجلسة" },

  // Finances
  "fin.title": { en: "Finances", ar: "المالية" },
  "fin.subtitle": { en: "Track your clinic's financial performance and transactions.", ar: "تتبع الأداء المالي لعيادتك والمعاملات." },
  "fin.stats.income": { en: "Total Income", ar: "إجمالي الدخل" },
  "fin.stats.expenses": { en: "Total Expenses", ar: "إجمالي المصروفات" },
  "fin.stats.net": { en: "Net Profit", ar: "صافي الربح" },
  "fin.transactions.title": { en: "Recent Transactions", ar: "المعاملات الأخيرة" },
  "fin.transactions.empty": { en: "No transactions found", ar: "لم يتم العثور على معاملات" },
  "fin.transactions.date": { en: "Date", ar: "التاريخ" },
  "fin.transactions.desc": { en: "Description", ar: "الوصف" },
  "fin.transactions.amount": { en: "Amount", ar: "المبلغ" },
  "fin.transactions.type": { en: "Type", ar: "النوع" },
  "fin.type.income": { en: "Income", ar: "دخل" },
  "fin.type.expense": { en: "Expense", ar: "مصروف" },

  // Appointments
  "appt.title": { en: "Appointments", ar: "المواعيد" },
  "appt.subtitle": { en: "Manage your clinic's schedule and bookings.", ar: "أدِر جدول عيادتك والحجوزات." },
  "appt.new": { en: "New Appointment", ar: "موعد جديد" },
  "appt.calendar": { en: "Calendar View", ar: "عرض التقويم" },
  "appt.list": { en: "List View", ar: "عرض القائمة" },
  "appt.empty": { en: "No appointments scheduled", ar: "لا توجد مواعيد مجدولة" },
  "appt.date": { en: "Date", ar: "التاريخ" },
  "appt.time": { en: "Time", ar: "الوقت" },
  "appt.patient": { en: "Patient", ar: "المريض" },
  "appt.type": { en: "Type", ar: "النوع" },
  "appt.status": { en: "Status", ar: "الحالة" },
  "appt.actions": { en: "Actions", ar: "الإجراءات" },

  // Pending Activation
  "pending.title": { en: "Account Pending Activation", ar: "الحساب في انتظار التفعيل" },
  "pending.subtitle": { en: "Your clinic trial is being processed.", ar: "جاري معالجة فترة تجربة عيادتك." },
  "pending.msg": { en: "Our team is reviewing your registration. Your account will be activated shortly.", ar: "يقوم فريقنا بمراجعة تسجيلك. سيتم تفعيل حسابك قريباً." },
  "pending.whatsapp": { en: "Contact support via WhatsApp", ar: "تواصل مع الدعم عبر واتساب" },
  "pending.logout": { en: "Sign Out", ar: "تسجيل الخروج" },

  // Team
  "team.title": { en: "Team Management", ar: "إدارة الفريق" },
  "team.subtitle": { en: "Manage your clinic staff and their access roles.", ar: "أدِر موظفي عيادتك وأدوار وصولهم." },
  "team.plan.premium": { en: "Premium Plan", ar: "الخطة المميزة" },
  "team.plan.trial": { en: "Free Trial", ar: "تجربة مجانية" },
  "team.plan.basic": { en: "Basic Plan", ar: "الخطة الأساسية" },
  "team.plan.expired": { en: "Plan Expired", ar: "انتهت الخطة" },
  "team.capacity.title": { en: "Team Capacity", ar: "سعة الفريق" },
  "team.capacity.note.prefix": { en: "Your", ar: "خطتك" },
  "team.capacity.note.suffix": { en: "allows up to", ar: "تسمح بحد أقصى" },
  "team.capacity.members": { en: "team members", ar: "أعضاء فريق" },
  "team.capacity.upgrade": { en: "Upgrade for more slots", ar: "رقي للحصول على المزيد" },
  "team.invite.title": { en: "Invite Member", ar: "دعوة عضو" },
  "team.invite.limitMsg": { en: "You have reached your team member limit. Upgrade to invite more.", ar: "لقد وصلت إلى الحد الأقصى لأعضاء الفريق. رقي لدعوة المزيد." },
  "team.invite.name": { en: "Name", ar: "الاسم" },
  "team.invite.namePh": { en: "Full name", ar: "الاسم الكامل" },
  "team.invite.email": { en: "Email", ar: "البريد الإلكتروني" },
  "team.invite.role": { en: "Role", ar: "الدور" },
  "team.role.secretary": { en: "Secretary", ar: "سكرتارية" },
  "team.role.nurse": { en: "Nurse", ar: "تمريض" },
  "team.role.admin": { en: "Admin", ar: "مدير" },
  "team.invite.send": { en: "Send Invite", ar: "إرسال الدعوة" },
  "team.pending.title": { en: "Pending Invitations", ar: "دعوات معلقة" },
  "team.pending.empty": { en: "No pending invitations", ar: "لا توجد دعوات معلقة" },
  "team.copied": { en: "Copied", ar: "تم النسخ" },
  "team.copyLink": { en: "Copy Link", ar: "نسخ الرابط" },
  "team.members.title": { en: "Active Members", ar: "الأعضاء النشطون" },
  "team.toast.inviteCreated": { en: "Invitation sent successfully", ar: "تم إرسال الدعوة بنجاح" },
  "team.toast.limitReached": { en: "Team limit reached", ar: "تم الوصول لحد الفريق" },
  "team.toast.duplicate": { en: "Email already invited", ar: "تمت دعوة هذا البريد مسبقاً" },
  "team.toast.failed": { en: "Failed to send invitation", ar: "فشل إرسال الدعوة" },
  "team.toast.failedTitle": { en: "Error", ar: "خطأ" },
  "team.toast.revoked": { en: "Invitation revoked", ar: "تم إلغاء الدعوة" },
  "team.confirm.remove": { en: "Are you sure you want to remove this member?", ar: "هل أنت متأكد من إزالة هذا العضو؟" },
  "team.toast.removed": { en: "Member removed", ar: "تم إزالة العضو" },
  "team.toast.copied": { en: "Link copied to clipboard", ar: "تم نسخ الرابط" },
  "team.toast.copyFailed": { en: "Failed to copy link", ar: "فشل نسخ الرابط" },

  // Settings
  "settings.title": { en: "Settings", ar: "الإعدادات" },
  "settings.profile.title": { en: "Profile", ar: "الملف الشخصي" },
  "settings.profile.specialty": { en: "Medical Specialty", ar: "التخصص الطبي" },
  "settings.profile.specialtyDesc": { en: "Shown on every prescription you issue (e.g. Cardiology, Pediatrics, Internal Medicine).", ar: "يظهر في كل وصفة طبية تصدرها (مثل: القلب، الأطفال، الباطنة)." },
  "settings.profile.specialtyPh": { en: "e.g. General Practitioner", ar: "مثال: ممارس عام" },
  "settings.profile.save": { en: "Save", ar: "حفظ" },
  "settings.profile.saving": { en: "Saving...", ar: "جاري الحفظ..." },
  "settings.profile.updated": { en: "Specialty updated", ar: "تم تحديث التخصص" },
  "settings.clinic.title": { en: "Clinic Identity", ar: "هوية العيادة" },
  "settings.clinic.desc": { en: "Shown on every prescription header and footer (PDF, print, and WhatsApp).", ar: "تظهر في رأس وتذييل كل وصفة طبية (PDF، طباعة، واتساب)." },
  "settings.clinic.name": { en: "Clinic Name *", ar: "اسم العيادة *" },
  "settings.clinic.namePh": { en: "e.g. ClinicSquad Medical Center", ar: "مثال: مركز كلينيك سكواد الطبي" },
  "settings.clinic.phone": { en: "Phone", ar: "الهاتف" },
  "settings.clinic.phonePh": { en: "e.g. +20 123 456 7890", ar: "مثال: 01234567890" },
  "settings.clinic.address": { en: "Address", ar: "العنوان" },
  "settings.clinic.addressPh": { en: "Street, City, Country", ar: "الشارع، المدينة، الدولة" },
  "settings.clinic.save": { en: "Save Identity", ar: "حفظ الهوية" },
  "settings.clinic.updated": { en: "Clinic identity updated", ar: "تم تحديث هوية العيادة" },
  "settings.info.title": { en: "Clinic Information", ar: "معلومات العيادة" },
  "settings.info.name": { en: "Clinic Name", ar: "اسم العيادة" },
  "settings.info.status": { en: "Account Status", ar: "حالة الحساب" },
  "settings.info.sub": { en: "Subscription", ar: "الاشتراك" },
  "settings.info.trialEnds": { en: "Trial Ends", ar: "تنتهي التجربة" },
  "settings.info.registered": { en: "Registered", ar: "تاريخ التسجيل" },
  "settings.pw.title": { en: "Change Password", ar: "تغيير كلمة المرور" },
  "settings.pw.current": { en: "Current Password", ar: "كلمة المرور الحالية" },
  "settings.pw.new": { en: "New Password", ar: "كلمة المرور الجديدة" },
  "settings.pw.confirm": { en: "Confirm New Password", ar: "تأكيد كلمة المرور" },
  "settings.pw.change": { en: "Change Password", ar: "تغيير كلمة المرور" },
  "settings.pw.changing": { en: "Changing...", ar: "جاري التغيير..." },
  "settings.pw.changed": { en: "Password changed successfully", ar: "تم تغيير كلمة المرور بنجاح" },
  "settings.security.title": { en: "Security Log", ar: "سجل الأمان" },
  "settings.security.desc": { en: "Recent account activity and sign-in events.", ar: "نشاط الحساب الأخير وأحداث تسجيل الدخول." },
  "settings.security.empty": { en: "No activity recorded yet", ar: "لا يوجد نشاط مسجل بعد" },

  // Insights
  "insights.title": { en: "Insights", ar: "التحليلات" },
  "insights.subtitle": { en: "Performance overview for your clinic", ar: "نظرة عامة على أداء عيادتك" },
  "insights.metric.patients": { en: "Total Patients", ar: "إجمالي المرضى" },
  "insights.metric.newPatients": { en: "this month", ar: "هذا الشهر" },
  "insights.metric.completion": { en: "Completion Rate", ar: "معدل الإتمام" },
  "insights.metric.completedOf": { en: "completed", ar: "مكتمل" },
  "insights.metric.revenue": { en: "Monthly Revenue", ar: "الإيرادات الشهرية" },
  "insights.metric.expenses": { en: "expenses", ar: "مصروفات" },
  "insights.metric.upcoming": { en: "Upcoming", ar: "قادم" },
  "insights.metric.today": { en: "today", ar: "اليوم" },
  "insights.busiest.dayTitle": { en: "Busiest Day This Month", ar: "أكثر الأيام ازدحاماً هذا الشهر" },
  "insights.busiest.dayPeak": { en: "peak load", ar: "ذروة العمل" },
  "insights.busiest.weekdayTitle": { en: "Busiest Weekday (All Time)", ar: "أكثر أيام الأسبوع ازدحاماً (دائماً)" },
  "insights.busiest.weekdayHist": { en: "historically", ar: "تاريخياً" },
  "insights.chart.appointmentsTitle": { en: "Appointments by Day", ar: "المواعيد حسب اليوم" },
  "insights.chart.appointmentsSub": { en: "Number of appointments per calendar day this month", ar: "عدد المواعيد لكل يوم تقويمي هذا الشهر" },
  "insights.chart.statusTitle": { en: "Appointment Status", ar: "حالة المواعيد" },
  "insights.chart.statusSub": { en: "Breakdown of visits by status", ar: "تحليل الزيارات حسب الحالة" },
  "insights.chart.revenueTitle": { en: "Revenue vs Expenses", ar: "الإيرادات مقابل المصروفات" },
  "insights.chart.revenueSub": { en: "Monthly financial performance", ar: "الأداء المالي الشهري" },
  "insights.premium.title": { en: "Premium Feature", ar: "ميزة متقدمة" },
  "insights.premium.desc": { en: "Insights and advanced analytics are available on the Premium plan. Upgrade to unlock performance dashboards, busy-day trends, and revenue charts.", ar: "التحليلات والبيانات المتقدمة متاحة في الخطة المميزة. رقي لفتح لوحات الأداء واتجاهات الأيام المزدحمة ورسوم الإيرادات." },
  "insights.premium.upgrade": { en: "Upgrade to Premium", ar: "الترقية للمميزة" },

  // Admin
  "admin.title": { en: "Platform Admin", ar: "مدير المنصة" },
  "admin.subtitle": { en: "Overview of all clinics, subscriptions, and platform activity", ar: "نظرة عامة على جميع العيادات والاشتراكات ونشاط المنصة" },
  "admin.kpi.clinics": { en: "Clinics", ar: "العيادات" },
  "admin.kpi.active": { en: "active", ar: "نشط" },
  "admin.kpi.users": { en: "Users", ar: "المستخدمين" },
  "admin.kpi.patients": { en: "patients", ar: "مريض" },
  "admin.kpi.new": { en: "New (7d)", ar: "جديد (7 أيام)" },
  "admin.kpi.trialEnding": { en: "Trial ending ≤3d", ar: "تنتهي التجربة ≤3 أيام" },
  "admin.kpi.pendingPayments": { en: "Pending payments", ar: "مدفوعات معلقة" },
  "admin.kpi.revenue": { en: "Revenue (confirmed)", ar: "الإيرادات (المؤكدة)" },
  "admin.pending.title": { en: "Pending Approvals", ar: "الموافقات المعلقة" },
  "admin.pending.empty": { en: "No clinics pending approval", ar: "لا توجد عيادات في انتظار الموافقة" },
  "admin.pending.activate": { en: "Activate Trial", ar: "تفعيل التجربة" },
  "admin.pending.activating": { en: "Activating...", ar: "جاري التفعيل..." },
  "admin.revenue.title": { en: "Monthly Revenue", ar: "الإيرادات الشهرية" },
  "admin.revenue.current": { en: "Current month revenue", ar: "إيرادات الشهر الحالي" },
  "admin.revenue.allYears": { en: "All Years", ar: "كل السنوات" },
  "admin.revenue.allMonths": { en: "All Months", ar: "كل الشهور" },
  "admin.plans.title": { en: "Subscribers by Plan", ar: "المشتركين حسب الخطة" },
  "admin.plans.subtitle": { en: "Click a plan to see its subscribers", ar: "اضغط على الخطة لرؤية المشتركين" },
  "admin.plans.trial.label": { en: "Free Trial", ar: "تجربة مجانية" },
  "admin.plans.trial.sub": { en: "15-day evaluation", ar: "تقييم 15 يوماً" },
  "admin.plans.basic.label": { en: "Basic Plan", ar: "الخطة الأساسية" },
  "admin.plans.basic.sub": { en: "200 EGP / month", ar: "200 جنيه / شهر" },
  "admin.plans.premium.label": { en: "Premium Plan", ar: "الخطة المميزة" },
  "admin.plans.premium.sub": { en: "400 EGP / month", ar: "400 جنيه / شهر" },
  "admin.clinics.title": { en: "All Clinics", ar: "كل العيادات" },
  "admin.clinics.searchPh": { en: "Search clinics...", ar: "البحث عن العيادات..." },
  "admin.clinics.name": { en: "Clinic Name", ar: "اسم العيادة" },
  "admin.clinics.owner": { en: "Owner", ar: "المالك" },
  "admin.clinics.status": { en: "Status", ar: "الحالة" },
  "admin.clinics.sub": { en: "Subscription", ar: "الاشتراك" },
  "admin.clinics.joined": { en: "Joined", ar: "انضم في" },
  "admin.clinics.actions": { en: "Actions", ar: "الإجراءات" },
  "admin.clinics.block": { en: "Block", ar: "حظر" },
  "admin.clinics.blocked": { en: "Blocked", ar: "محظور" },
  "admin.clinics.active": { en: "Active", ar: "نشط" },
  "admin.clinics.pending": { en: "Pending", ar: "معلق" },
};

const LangContext = createContext<LangContextType | undefined>(undefined);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem("clinic_lang");
    return (saved as Lang) || "en";
  });

  useEffect(() => {
    localStorage.setItem("clinic_lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const t = (key: string) => {
    return translations[key]?.[lang] || key;
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LangContext);
  if (!context) throw new Error("useLang must be used within LangProvider");
  return context;
}
